In [1]:
import pandas as pd
import numpy as np

In [2]:
#toto neni z W3Schools, ale spis Stack Overflow

In [3]:
df = pd.read_csv('data.csv')
df.drop_duplicates(inplace = True)

# create column with index
df["ID"] = df.index

print(df.to_string())

    Duration          Date  Pulse  Maxpulse  Calories  ID
0         60  '2020/12/01'    110       130     409.1   0
1         60  '2020/12/02'    117       145     479.0   1
2         60  '2020/12/03'    103       135     340.0   2
3         45  '2020/12/04'    109       175     282.4   3
4         45  '2020/12/05'    117       148     406.0   4
5         60  '2020/12/06'    102       127     300.0   5
6         60  '2020/12/07'    110       136     374.0   6
7        450  '2020/12/08'    104       134     253.3   7
8         30  '2020/12/09'    109       133     195.1   8
9         60  '2020/12/10'     98       124     269.0   9
10        60  '2020/12/11'    103       147     329.3  10
11        60  '2020/12/12'    100       120     250.7  11
13        60  '2020/12/13'    106       128     345.3  13
14        60  '2020/12/14'    104       132     379.3  14
15        60  '2020/12/15'     98       123     275.0  15
16        60  '2020/12/16'     98       120     215.2  16
17        60  '2020/12/17'    100       120     300.0  17
18        45  '2020/12/18'     90       112       NaN  18
19        60  '2020/12/19'    103       123     323.0  19
20        45  '2020/12/20'     97       125     243.0  20
21        60  '2020/12/21'    108       131     364.2  21
22        45           NaN    100       119     282.0  22
23        60  '2020/12/23'    130       101     300.0  23
24        45  '2020/12/24'    105       132     246.0  24
25        60  '2020/12/25'    102       126     334.5  25
26        60      20201226    100       120     250.0  26
27        60  '2020/12/27'     92       118     241.0  27
28        60  '2020/12/28'    103       132       NaN  28
29        60  '2020/12/29'    100       132     280.0  29
30        60  '2020/12/30'    102       129     380.3  30
31        60  '2020/12/31'     92       115     243.0  31

In [4]:
# create column with rowid

print(df.index.size) #Notice that row 12 has been removed from the result

df["ID0"] = np.array(np.linspace(0, df.index.size - 1,df.index.size), np.int64)
df["ID1"] = np.array(np.linspace(1, df.index.size, df.index.size), np.int64)

print(df.to_string())

31
    Duration          Date  Pulse  Maxpulse  Calories  ID  ID0  ID1
0         60  '2020/12/01'    110       130     409.1   0    0    1
1         60  '2020/12/02'    117       145     479.0   1    1    2
2         60  '2020/12/03'    103       135     340.0   2    2    3
3         45  '2020/12/04'    109       175     282.4   3    3    4
4         45  '2020/12/05'    117       148     406.0   4    4    5
5         60  '2020/12/06'    102       127     300.0   5    5    6
6         60  '2020/12/07'    110       136     374.0   6    6    7
7        450  '2020/12/08'    104       134     253.3   7    7    8
8         30  '2020/12/09'    109       133     195.1   8    8    9
9         60  '2020/12/10'     98       124     269.0   9    9   10
10        60  '2020/12/11'    103       147     329.3  10   10   11
11        60  '2020/12/12'    100       120     250.7  11   11   12
13        60  '2020/12/13'    106       128     345.3  13   12   13
14        60  '2020/12/14'    104       132     379.3  14   13   14
15        60  '2020/12/15'     98       123     275.0  15   14   15
16        60  '2020/12/16'     98       120     215.2  16   15   16
17        60  '2020/12/17'    100       120     300.0  17   16   17
18        45  '2020/12/18'     90       112       NaN  18   17   18
19        60  '2020/12/19'    103       123     323.0  19   18   19
20        45  '2020/12/20'     97       125     243.0  20   19   20
21        60  '2020/12/21'    108       131     364.2  21   20   21
22        45           NaN    100       119     282.0  22   21   22
23        60  '2020/12/23'    130       101     300.0  23   22   23
24        45  '2020/12/24'    105       132     246.0  24   23   24
25        60  '2020/12/25'    102       126     334.5  25   24   25
26        60      20201226    100       120     250.0  26   25   26
27        60  '2020/12/27'     92       118     241.0  27   26   27
28        60  '2020/12/28'    103       132       NaN  28   27   28
29        60  '2020/12/29'    100       132     280.0  29   28   29
30        60  '2020/12/30'    102       129     380.3  30   29   30
31        60  '2020/12/31'     92       115     243.0  31   30   31