In [43]:
#pip install psycopg2-binary
#pip install psycopg2

In [2]:
import psycopg2
import pandas as pd

In [3]:
# Connect to your postgres DB
conn = psycopg2.connect("dbname=test user=funka password=funka")

In [4]:
# Open a cursor to perform database operations
cur = conn.cursor()

In [5]:
# Execute a query
#cur.execute("SELECT * FROM customers")
cur.execute("SELECT * FROM orders") #int, datetime
#cur.execute("SELECT * FROM products") #int, decimal

In [6]:
# Retrieve query results
records = cur.fetchall()

In [7]:
records

[(10248, 90, datetime.date(2021, 7, 4)),
 (10249, 81, datetime.date(2021, 7, 5)),
 (10250, 34, datetime.date(2021, 7, 8)),
 (10251, 84, datetime.date(2021, 7, 8)),
 (10252, 76, datetime.date(2021, 7, 9)),
 (10253, 34, datetime.date(2021, 7, 10)),
 (10254, 14, datetime.date(2021, 7, 11)),
 (10255, 68, datetime.date(2021, 7, 12)),
 (10256, 88, datetime.date(2021, 7, 15)),
 (10257, 35, datetime.date(2021, 7, 16)),
 (10258, 20, datetime.date(2021, 7, 17)),
 (10259, 13, datetime.date(2021, 7, 18)),
 (10260, 55, datetime.date(2021, 7, 19)),
 (10261, 61, datetime.date(2021, 7, 19)),
 (10262, 65, datetime.date(2021, 7, 22)),
 (10263, 20, datetime.date(2021, 7, 23)),
 (10264, 24, datetime.date(2021, 7, 24)),
 (10265, 7, datetime.date(2021, 7, 25)),
 (10266, 87, datetime.date(2021, 7, 26)),
 (10267, 25, datetime.date(2021, 7, 29)),
 (10268, 33, datetime.date(2021, 7, 30)),
 (10269, 89, datetime.date(2021, 7, 31)),
 (10270, 87, datetime.date(2021, 8, 1)),
 (10271, 75, datetime.date(2021, 8, 1)),
 (10272, 65, datetime.date(2021, 8, 2)),
 (10273, 63, datetime.date(2021, 8, 5)),
 (10274, 85, datetime.date(2021, 8, 6)),
 (10275, 49, datetime.date(2021, 8, 7)),
 (10276, 80, datetime.date(2021, 8, 8)),
 (10277, 52, datetime.date(2021, 8, 9)),
 (10278, 5, datetime.date(2021, 8, 12)),
 (10279, 44, datetime.date(2021, 8, 13)),
 (10280, 5, datetime.date(2021, 8, 14)),
 (10281, 69, datetime.date(2021, 8, 14)),
 (10282, 69, datetime.date(2021, 8, 15)),
 (10283, 46, datetime.date(2021, 8, 16)),
 (10284, 44, datetime.date(2021, 8, 19)),
 (10285, 63, datetime.date(2021, 8, 20)),
 (10286, 63, datetime.date(2021, 8, 21)),
 (10287, 67, datetime.date(2021, 8, 22)),
 (10288, 66, datetime.date(2021, 8, 23)),
 (10289, 11, datetime.date(2021, 8, 26)),
 (10290, 15, datetime.date(2021, 8, 27)),
 (10291, 61, datetime.date(2021, 8, 27)),
 (10292, 81, datetime.date(2021, 8, 28)),
 (10293, 80, datetime.date(2021, 8, 29)),
 (10294, 65, datetime.date(2021, 8, 30)),
 (10295, 85, datetime.date(2021, 9, 2)),
 (10296, 46, datetime.date(2021, 9, 3)),
 (10297, 7, datetime.date(2021, 9, 4)),
 (10298, 37, datetime.date(2021, 9, 5)),
 (10299, 67, datetime.date(2021, 9, 6)),
 (10300, 49, datetime.date(2021, 9, 9)),
 (10301, 86, datetime.date(2021, 9, 9)),
 (10302, 76, datetime.date(2021, 9, 10)),
 (10303, 30, datetime.date(2021, 9, 11)),
 (10304, 80, datetime.date(2021, 9, 12)),
 (10305, 55, datetime.date(2021, 9, 13)),
 (10306, 69, datetime.date(2021, 9, 16)),
 (10307, 48, datetime.date(2021, 9, 17)),
 (10308, 2, datetime.date(2021, 9, 18)),
 (10309, 37, datetime.date(2021, 9, 19)),
 (10310, 77, datetime.date(2021, 9, 20)),
 (10311, 18, datetime.date(2021, 9, 20)),
 (10312, 86, datetime.date(2021, 9, 23)),
 (10313, 63, datetime.date(2021, 9, 24)),
 (10314, 65, datetime.date(2021, 9, 25)),
 (10315, 38, datetime.date(2021, 9, 26)),
 (10316, 65, datetime.date(2021, 9, 27)),
 (10317, 48, datetime.date(2021, 9, 30)),
 (10318, 38, datetime.date(2021, 10, 1)),
 (10319, 80, datetime.date(2021, 10, 2)),
 (10320, 87, datetime.date(2021, 10, 3)),
 (10321, 38, datetime.date(2021, 10, 3)),
 (10322, 58, datetime.date(2021, 10, 4)),
 (10323, 39, datetime.date(2021, 10, 7)),
 (10324, 71, datetime.date(2021, 10, 8)),
 (10325, 39, datetime.date(2021, 10, 9)),
 (10326, 8, datetime.date(2021, 10, 10)),
 (10327, 24, datetime.date(2021, 10, 11)),
 (10328, 28, datetime.date(2021, 10, 14)),
 (10329, 75, datetime.date(2021, 10, 15)),
 (10330, 46, datetime.date(2021, 10, 16)),
 (10331, 9, datetime.date(2021, 10, 16)),
 (10332, 51, datetime.date(2021, 10, 17)),
 (10333, 87, datetime.date(2021, 10, 18)),
 (10334, 84, datetime.date(2021, 10, 21)),
 (10335, 37, datetime.date(2021, 10, 22)),
 (10336, 60, datetime.date(2021, 10, 23)),
 (10337, 25, datetime.date(2021, 10, 24)),
 (10338, 55, datetime.date(2021, 10, 25)),
 (10339, 51, datetime.date(2021, 10, 28)),
 (10340, 9, datetime.date(2021, 10, 29)),
 (10341, 73, datetime.date(2021, 10, 29)),
 (10342, 25, datetime.date(2021, 10, 30)),
 (10343, 44, datetime.date(2021, 10, 31)),
 (10344, 89, datetime.date(2021, 11, 1)),
 (10345, 63, datetime.date(2021, 11, 4)),
 (10346, 65, datetime.date(2021, 11, 5)),
 (10347, 21, datetime.date(2021, 11, 6)),
 (10348, 86, datetime.date(2021, 11, 7)),
 (10349, 75, datetime.date(2021, 11, 8)),
 (10350, 41, datetime.date(2021, 11, 11)),
 (10351, 20, datetime.date(2021, 11, 11)),
 (10352, 28, datetime.date(2021, 11, 12)),
 (10353, 59, datetime.date(2021, 11, 13)),
 (10354, 58, datetime.date(2021, 11, 14)),
 (10355, 4, datetime.date(2021, 11, 15)),
 (10356, 86, datetime.date(2021, 11, 18)),
 (10357, 46, datetime.date(2021, 11, 19)),
 (10358, 41, datetime.date(2021, 11, 20)),
 (10359, 72, datetime.date(2021, 11, 21)),
 (10360, 7, datetime.date(2021, 11, 22)),
 (10361, 63, datetime.date(2021, 11, 22)),
 (10362, 9, datetime.date(2021, 11, 25)),
 (10363, 17, datetime.date(2021, 11, 26)),
 (10364, 19, datetime.date(2021, 11, 26)),
 (10365, 3, datetime.date(2021, 11, 27)),
 (10366, 29, datetime.date(2021, 11, 28)),
 (10367, 83, datetime.date(2021, 11, 28)),
 (10368, 20, datetime.date(2021, 11, 29)),
 (10369, 75, datetime.date(2021, 12, 2)),
 (10370, 14, datetime.date(2021, 12, 3)),
 (10371, 41, datetime.date(2021, 12, 3)),
 (10372, 62, datetime.date(2021, 12, 4)),
 (10373, 37, datetime.date(2021, 12, 5)),
 (10374, 91, datetime.date(2021, 12, 5)),
 (10375, 36, datetime.date(2021, 12, 6)),
 (10376, 51, datetime.date(2021, 12, 9)),
 (10377, 72, datetime.date(2021, 12, 9)),
 (10378, 24, datetime.date(2021, 12, 10)),
 (10379, 61, datetime.date(2021, 12, 11)),
 (10380, 37, datetime.date(2021, 12, 12)),
 (10381, 46, datetime.date(2021, 12, 12)),
 (10382, 20, datetime.date(2021, 12, 13)),
 (10383, 4, datetime.date(2021, 12, 16)),
 (10384, 5, datetime.date(2021, 12, 16)),
 (10385, 75, datetime.date(2021, 12, 17)),
 (10386, 21, datetime.date(2021, 12, 18)),
 (10387, 70, datetime.date(2021, 12, 18)),
 (10388, 72, datetime.date(2021, 12, 19)),
 (10389, 10, datetime.date(2021, 12, 20)),
 (10390, 20, datetime.date(2021, 12, 23)),
 (10391, 17, datetime.date(2021, 12, 23)),
 (10392, 59, datetime.date(2021, 12, 24)),
 (10393, 71, datetime.date(2021, 12, 25)),
 (10394, 36, datetime.date(2021, 12, 25)),
 (10395, 35, datetime.date(2021, 12, 26)),
 (10396, 25, datetime.date(2021, 12, 27)),
 (10397, 60, datetime.date(2021, 12, 27)),
 (10398, 71, datetime.date(2021, 12, 30)),
 (10399, 83, datetime.date(2021, 12, 31)),
 (10400, 19, datetime.date(2022, 1, 1)),
 (10401, 65, datetime.date(2022, 1, 1)),
 (10402, 20, datetime.date(2022, 1, 2)),
 (10403, 20, datetime.date(2022, 1, 3)),
 (10404, 49, datetime.date(2022, 1, 3)),
 (10405, 47, datetime.date(2022, 1, 6)),
 (10406, 62, datetime.date(2022, 1, 7)),
 (10407, 56, datetime.date(2022, 1, 7)),
 (10408, 23, datetime.date(2022, 1, 8)),
 (10409, 54, datetime.date(2022, 1, 9)),
 (10410, 10, datetime.date(2022, 1, 10)),
 (10411, 10, datetime.date(2022, 1, 10)),
 (10412, 87, datetime.date(2022, 1, 13)),
 (10413, 41, datetime.date(2022, 1, 14)),
 (10414, 21, datetime.date(2022, 1, 14)),
 (10415, 36, datetime.date(2022, 1, 15)),
 (10416, 87, datetime.date(2022, 1, 16)),
 (10417, 73, datetime.date(2022, 1, 16)),
 (10418, 63, datetime.date(2022, 1, 17)),
 (10419, 68, datetime.date(2022, 1, 20)),
 (10420, 88, datetime.date(2022, 1, 21)),
 (10421, 61, datetime.date(2022, 1, 21)),
 (10422, 27, datetime.date(2022, 1, 22)),
 (10423, 31, datetime.date(2022, 1, 23)),
 (10424, 51, datetime.date(2022, 1, 23)),
 (10425, 41, datetime.date(2022, 1, 24)),
 (10426, 29, datetime.date(2022, 1, 27)),
 (10427, 59, datetime.date(2022, 1, 27)),
 (10428, 66, datetime.date(2022, 1, 28)),
 (10429, 37, datetime.date(2022, 1, 29)),
 (10430, 20, datetime.date(2022, 1, 30)),
 (10431, 10, datetime.date(2022, 1, 30)),
 (10432, 75, datetime.date(2022, 1, 31)),
 (10433, 60, datetime.date(2022, 2, 3)),
 (10434, 24, datetime.date(2022, 2, 3)),
 (10435, 16, datetime.date(2022, 2, 4)),
 (10436, 7, datetime.date(2022, 2, 5)),
 (10437, 87, datetime.date(2022, 2, 5)),
 (10438, 79, datetime.date(2022, 2, 6)),
 (10439, 51, datetime.date(2022, 2, 7)),
 (10440, 71, datetime.date(2022, 2, 10)),
 (10441, 55, datetime.date(2022, 2, 10)),
 (10442, 20, datetime.date(2022, 2, 11)),
 (10443, 66, datetime.date(2022, 2, 12)),
 (10444, 5, datetime.date(2022, 2, 12)),
 (10445, 5, datetime.date(2022, 2, 13)),
 (10446, 79, datetime.date(2022, 2, 14)),
 (10447, 67, datetime.date(2022, 2, 14)),
 (10448, 64, datetime.date(2022, 2, 17)),
 (10449, 7, datetime.date(2022, 2, 18)),
 (10450, 84, datetime.date(2022, 2, 19)),
 (10451, 63, datetime.date(2022, 2, 19)),
 (10452, 71, datetime.date(2022, 2, 20)),
 (10453, 4, datetime.date(2022, 2, 21)),
 (10454, 41, datetime.date(2022, 2, 21)),
 (10455, 87, datetime.date(2022, 2, 24)),
 (10456, 39, datetime.date(2022, 2, 25)),
 (10457, 39, datetime.date(2022, 2, 25)),
 (10458, 76, datetime.date(2022, 2, 26)),
 (10459, 84, datetime.date(2022, 2, 27)),
 (10460, 24, datetime.date(2022, 2, 28)),
 (10461, 46, datetime.date(2022, 2, 28)),
 (10462, 16, datetime.date(2022, 3, 3)),
 (10463, 76, datetime.date(2022, 3, 4)),
 (10464, 28, datetime.date(2022, 3, 4)),
 (10465, 83, datetime.date(2022, 3, 5)),
 (10466, 15, datetime.date(2022, 3, 6)),
 (10467, 49, datetime.date(2022, 3, 6)),
 (10468, 39, datetime.date(2022, 3, 7)),
 (10469, 89, datetime.date(2022, 3, 10)),
 (10470, 9, datetime.date(2022, 3, 11)),
 (10471, 11, datetime.date(2022, 3, 11)),
 (10472, 72, datetime.date(2022, 3, 12)),
 (10473, 38, datetime.date(2022, 3, 13)),
 (10474, 58, datetime.date(2022, 3, 13)),
 (10475, 76, datetime.date(2022, 3, 14)),
 (10476, 35, datetime.date(2022, 3, 17)),
 (10477, 60, datetime.date(2022, 3, 17)),
 (10478, 84, datetime.date(2022, 3, 18)),
 (10479, 65, datetime.date(2022, 3, 19)),
 (10480, 23, datetime.date(2022, 3, 20)),
 (10481, 67, datetime.date(2022, 3, 20)),
 (10482, 43, datetime.date(2022, 3, 21)),
 (10483, 89, datetime.date(2022, 3, 24)),
 (10484, 11, datetime.date(2022, 3, 24)),
 (10485, 47, datetime.date(2022, 3, 25)),
 (10486, 35, datetime.date(2022, 3, 26)),
 (10487, 62, datetime.date(2022, 3, 26)),
 (10488, 25, datetime.date(2022, 3, 27)),
 (10489, 59, datetime.date(2022, 3, 28)),
 (10490, 35, datetime.date(2022, 3, 31)),
 (10491, 28, datetime.date(2022, 3, 31)),
 (10492, 10, datetime.date(2022, 4, 1)),
 (10493, 41, datetime.date(2022, 4, 2)),
 (10494, 15, datetime.date(2022, 4, 2)),
 (10495, 42, datetime.date(2022, 4, 3)),
 (10496, 81, datetime.date(2022, 4, 4)),
 (10497, 44, datetime.date(2022, 4, 4)),
 (10498, 35, datetime.date(2022, 4, 7)),
 (10499, 46, datetime.date(2022, 4, 8)),
 (10500, 41, datetime.date(2022, 4, 9)),
 (10501, 6, datetime.date(2022, 4, 9)),
 (10502, 58, datetime.date(2022, 4, 10)),
 (10503, 37, datetime.date(2022, 4, 11)),
 (10504, 89, datetime.date(2022, 4, 11)),
 (10505, 51, datetime.date(2022, 4, 14)),
 (10506, 39, datetime.date(2022, 4, 15)),
 (10507, 3, datetime.date(2022, 4, 15)),
 (10508, 56, datetime.date(2022, 4, 16)),
 (10509, 6, datetime.date(2022, 4, 17)),
 (10510, 71, datetime.date(2022, 4, 18)),
 (10511, 9, datetime.date(2022, 4, 18)),
 (10512, 21, datetime.date(2022, 4, 21)),
 (10513, 86, datetime.date(2022, 4, 22)),
 (10514, 20, datetime.date(2022, 4, 22)),
 (10515, 63, datetime.date(2022, 4, 23)),
 (10516, 37, datetime.date(2022, 4, 24)),
 (10517, 53, datetime.date(2022, 4, 24)),
 (10518, 80, datetime.date(2022, 4, 25)),
 (10519, 14, datetime.date(2022, 4, 28)),
 (10520, 70, datetime.date(2022, 4, 29)),
 (10521, 12, datetime.date(2022, 4, 29)),
 (10522, 44, datetime.date(2022, 4, 30)),
 (10523, 72, datetime.date(2022, 5, 1)),
 (10524, 5, datetime.date(2022, 5, 1)),
 (10525, 9, datetime.date(2022, 5, 2)),
 (10526, 87, datetime.date(2022, 5, 5)),
 (10527, 63, datetime.date(2022, 5, 5)),
 (10528, 32, datetime.date(2022, 5, 6)),
 (10529, 50, datetime.date(2022, 5, 7)),
 (10530, 59, datetime.date(2022, 5, 8)),
 (10531, 54, datetime.date(2022, 5, 8)),
 (10532, 19, datetime.date(2022, 5, 9)),
 (10533, 24, datetime.date(2022, 5, 12)),
 (10534, 44, datetime.date(2022, 5, 12)),
 (10535, 3, datetime.date(2022, 5, 13)),
 (10536, 44, datetime.date(2022, 5, 14)),
 (10537, 68, datetime.date(2022, 5, 14)),
 (10538, 11, datetime.date(2022, 5, 15)),
 (10539, 11, datetime.date(2022, 5, 16)),
 (10540, 63, datetime.date(2022, 5, 19)),
 (10541, 34, datetime.date(2022, 5, 19)),
 (10542, 39, datetime.date(2022, 5, 20)),
 (10543, 46, datetime.date(2022, 5, 21)),
 (10544, 48, datetime.date(2022, 5, 21)),
 (10545, 43, datetime.date(2022, 5, 22)),
 (10546, 84, datetime.date(2022, 5, 23)),
 (10547, 72, datetime.date(2022, 5, 23)),
 (10548, 79, datetime.date(2022, 5, 26)),
 (10549, 63, datetime.date(2022, 5, 27)),
 (10550, 30, datetime.date(2022, 5, 28)),
 (10551, 28, datetime.date(2022, 5, 28)),
 (10552, 35, datetime.date(2022, 5, 29)),
 (10553, 87, datetime.date(2022, 5, 30)),
 (10554, 56, datetime.date(2022, 5, 30)),
 (10555, 71, datetime.date(2022, 6, 2)),
 (10556, 73, datetime.date(2022, 6, 3)),
 (10557, 44, datetime.date(2022, 6, 3)),
 (10558, 4, datetime.date(2022, 6, 4)),
 (10559, 7, datetime.date(2022, 6, 5)),
 (10560, 25, datetime.date(2022, 6, 6)),
 (10561, 24, datetime.date(2022, 6, 6)),
 (10562, 66, datetime.date(2022, 6, 9)),
 (10563, 67, datetime.date(2022, 6, 10)),
 (10564, 65, datetime.date(2022, 6, 10)),
 (10565, 51, datetime.date(2022, 6, 11)),
 (10566, 7, datetime.date(2022, 6, 12)),
 (10567, 37, datetime.date(2022, 6, 12)),
 (10568, 29, datetime.date(2022, 6, 13)),
 (10569, 65, datetime.date(2022, 6, 16)),
 (10570, 51, datetime.date(2022, 6, 17)),
 (10571, 20, datetime.date(2022, 6, 17)),
 (10572, 5, datetime.date(2022, 6, 18)),
 (10573, 3, datetime.date(2022, 6, 19)),
 (10574, 82, datetime.date(2022, 6, 19)),
 (10575, 52, datetime.date(2022, 6, 20)),
 (10576, 80, datetime.date(2022, 6, 23)),
 (10577, 82, datetime.date(2022, 6, 23)),
 (10578, 11, datetime.date(2022, 6, 24)),
 (10579, 45, datetime.date(2022, 6, 25)),
 (10580, 56, datetime.date(2022, 6, 26)),
 (10581, 21, datetime.date(2022, 6, 26)),
 (10582, 6, datetime.date(2022, 6, 27)),
 (10583, 87, datetime.date(2022, 6, 30)),
 (10584, 7, datetime.date(2022, 6, 30)),
 (10585, 88, datetime.date(2022, 7, 1)),
 (10586, 66, datetime.date(2022, 7, 2)),
 (10587, 61, datetime.date(2022, 7, 2)),
 (10588, 63, datetime.date(2022, 7, 3)),
 (10589, 32, datetime.date(2022, 7, 4)),
 (10590, 51, datetime.date(2022, 7, 7)),
 (10591, 83, datetime.date(2022, 7, 7)),
 (10592, 44, datetime.date(2022, 7, 8)),
 (10593, 44, datetime.date(2022, 7, 9)),
 (10594, 55, datetime.date(2022, 7, 9)),
 (10595, 20, datetime.date(2022, 7, 10)),
 (10596, 89, datetime.date(2022, 7, 11)),
 (10597, 59, datetime.date(2022, 7, 11)),
 (10598, 65, datetime.date(2022, 7, 14)),
 (10599, 11, datetime.date(2022, 7, 15)),
 (10600, 36, datetime.date(2022, 7, 16)),
 (10601, 35, datetime.date(2022, 7, 16)),
 (10602, 83, datetime.date(2022, 7, 17)),
 (10603, 71, datetime.date(2022, 7, 18)),
 (10604, 28, datetime.date(2022, 7, 18)),
 (10605, 51, datetime.date(2022, 7, 21)),
 (10606, 81, datetime.date(2022, 7, 22)),
 (10607, 71, datetime.date(2022, 7, 22)),
 (10608, 79, datetime.date(2022, 7, 23)),
 (10609, 18, datetime.date(2022, 7, 24)),
 (10610, 41, datetime.date(2022, 7, 25)),
 (10611, 91, datetime.date(2022, 7, 25)),
 (10612, 71, datetime.date(2022, 7, 28)),
 (10613, 35, datetime.date(2022, 7, 29)),
 (10614, 6, datetime.date(2022, 7, 29)),
 (10615, 90, datetime.date(2022, 7, 30)),
 (10616, 32, datetime.date(2022, 7, 31)),
 (10617, 32, datetime.date(2022, 7, 31)),
 (10618, 51, datetime.date(2022, 8, 1)),
 (10619, 51, datetime.date(2022, 8, 4)),
 (10620, 42, datetime.date(2022, 8, 5)),
 (10621, 38, datetime.date(2022, 8, 5)),
 (10622, 67, datetime.date(2022, 8, 6)),
 (10623, 25, datetime.date(2022, 8, 7)),
 (10624, 78, datetime.date(2022, 8, 7)),
 (10625, 2, datetime.date(2022, 8, 8)),
 (10626, 5, datetime.date(2022, 8, 11)),
 (10627, 71, datetime.date(2022, 8, 11)),
 (10628, 7, datetime.date(2022, 8, 12)),
 (10629, 30, datetime.date(2022, 8, 12)),
 (10630, 39, datetime.date(2022, 8, 13)),
 (10631, 41, datetime.date(2022, 8, 14)),
 (10632, 86, datetime.date(2022, 8, 14)),
 (10633, 20, datetime.date(2022, 8, 15)),
 (10634, 23, datetime.date(2022, 8, 15)),
 (10635, 49, datetime.date(2022, 8, 18)),
 (10636, 87, datetime.date(2022, 8, 19)),
 (10637, 62, datetime.date(2022, 8, 19)),
 (10638, 47, datetime.date(2022, 8, 20)),
 (10639, 70, datetime.date(2022, 8, 20)),
 (10640, 86, datetime.date(2022, 8, 21)),
 (10641, 35, datetime.date(2022, 8, 22)),
 (10642, 73, datetime.date(2022, 8, 22)),
 (10643, 1, datetime.date(2022, 8, 25)),
 (10644, 88, datetime.date(2022, 8, 25)),
 (10645, 34, datetime.date(2022, 8, 26)),
 (10646, 37, datetime.date(2022, 8, 27)),
 (10647, 61, datetime.date(2022, 8, 27)),
 (10648, 67, datetime.date(2022, 8, 28)),
 (10649, 50, datetime.date(2022, 8, 28)),
 (10650, 21, datetime.date(2022, 8, 29)),
 (10651, 86, datetime.date(2022, 9, 1)),
 (10652, 31, datetime.date(2022, 9, 1)),
 (10653, 25, datetime.date(2022, 9, 2)),
 (10654, 5, datetime.date(2022, 9, 2)),
 (10655, 66, datetime.date(2022, 9, 3)),
 (10656, 32, datetime.date(2022, 9, 4)),
 (10657, 71, datetime.date(2022, 9, 4)),
 (10658, 63, datetime.date(2022, 9, 5)),
 (10659, 62, datetime.date(2022, 9, 5)),
 (10660, 36, datetime.date(2022, 9, 8)),
 (10661, 37, datetime.date(2022, 9, 9)),
 (10662, 48, datetime.date(2022, 9, 9)),
 (10663, 9, datetime.date(2022, 9, 10)),
 (10664, 28, datetime.date(2022, 9, 10)),
 (10665, 48, datetime.date(2022, 9, 11)),
 (10666, 68, datetime.date(2022, 9, 12)),
 (10667, 20, datetime.date(2022, 9, 12)),
 (10668, 86, datetime.date(2022, 9, 15)),
 (10669, 73, datetime.date(2022, 9, 15)),
 (10670, 25, datetime.date(2022, 9, 16)),
 (10671, 26, datetime.date(2022, 9, 17)),
 (10672, 5, datetime.date(2022, 9, 17)),
 (10673, 90, datetime.date(2022, 9, 18)),
 (10674, 38, datetime.date(2022, 9, 18)),
 (10675, 25, datetime.date(2022, 9, 19)),
 (10676, 80, datetime.date(2022, 9, 22)),
 (10677, 3, datetime.date(2022, 9, 22)),
 (10678, 71, datetime.date(2022, 9, 23)),
 (10679, 7, datetime.date(2022, 9, 23)),
 (10680, 55, datetime.date(2022, 9, 24)),
 (10681, 32, datetime.date(2022, 9, 25)),
 (10682, 3, datetime.date(2022, 9, 25)),
 (10683, 18, datetime.date(2022, 9, 26)),
 (10684, 56, datetime.date(2022, 9, 26)),
 (10685, 31, datetime.date(2022, 9, 29)),
 (10686, 59, datetime.date(2022, 9, 30)),
 (10687, 37, datetime.date(2022, 9, 30)),
 (10688, 83, datetime.date(2022, 10, 1)),
 (10689, 5, datetime.date(2022, 10, 1)),
 (10690, 34, datetime.date(2022, 10, 2)),
 (10691, 63, datetime.date(2022, 10, 3)),
 (10692, 1, datetime.date(2022, 10, 3)),
 (10693, 89, datetime.date(2022, 10, 6)),
 (10694, 63, datetime.date(2022, 10, 6)),
 (10695, 90, datetime.date(2022, 10, 7)),
 (10696, 89, datetime.date(2022, 10, 8)),
 (10697, 47, datetime.date(2022, 10, 8)),
 (10698, 20, datetime.date(2022, 10, 9)),
 (10699, 52, datetime.date(2022, 10, 9)),
 (10700, 71, datetime.date(2022, 10, 10)),
 (10701, 37, datetime.date(2022, 10, 13)),
 (10702, 1, datetime.date(2022, 10, 13)),
 (10703, 24, datetime.date(2022, 10, 14)),
 (10704, 62, datetime.date(2022, 10, 14)),
 (10705, 35, datetime.date(2022, 10, 15)),
 (10706, 55, datetime.date(2022, 10, 16)),
 (10707, 4, datetime.date(2022, 10, 16)),
 (10708, 77, datetime.date(2022, 10, 17)),
 (10709, 31, datetime.date(2022, 10, 17)),
 (10710, 27, datetime.date(2022, 10, 20)),
 (10711, 71, datetime.date(2022, 10, 21)),
 (10712, 37, datetime.date(2022, 10, 21)),
 (10713, 71, datetime.date(2022, 10, 22)),
 (10714, 71, datetime.date(2022, 10, 22)),
 (10715, 9, datetime.date(2022, 10, 23)),
 (10716, 64, datetime.date(2022, 10, 24)),
 (10717, 25, datetime.date(2022, 10, 24)),
 (10718, 39, datetime.date(2022, 10, 27)),
 (10719, 45, datetime.date(2022, 10, 27)),
 (10720, 61, datetime.date(2022, 10, 28)),
 (10721, 63, datetime.date(2022, 10, 29)),
 (10722, 71, datetime.date(2022, 10, 29)),
 (10723, 89, datetime.date(2022, 10, 30)),
 (10724, 51, datetime.date(2022, 10, 30)),

In [8]:
len(cur.description)

3

In [9]:
field_names = [col[0] for col in cur.description]

In [10]:
field_names

['order_id', 'customer_id', 'order_date']

In [11]:
df = pd.DataFrame((tuple(t) for t in records))
df.columns = field_names

In [12]:
df

     order_id  customer_id  order_date
0       10248           90  2021-07-04
1       10249           81  2021-07-05
2       10250           34  2021-07-08
3       10251           84  2021-07-08
4       10252           76  2021-07-09
..        ...          ...         ...
825     11073           58  2023-05-05
826     11074           73  2023-05-06
827     11075           68  2023-05-06
828     11076            9  2023-05-06
829     11077           65  2023-05-06

[830 rows x 3 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     830 non-null    int64
 1   customer_id  830 non-null    int64
 2   order_date   830 non-null    object
dtypes: int64(2), object(1)
memory usage: 19.6+ KB

In [14]:
#df['price'] = pd.to_numeric(df['price'])
df['order_date'] = pd.to_datetime(df['order_date'])
#df['order_date'] = pd.to_datetime(df['order_date'], format='%Y-%m-%d') #format = 'mixed'
#df['order_date1'] = str(df['order_date'])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     830 non-null    int64
 1   customer_id  830 non-null    int64
 2   order_date   830 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(2)
memory usage: 19.6 KB

In [16]:
df

     order_id  customer_id order_date
0       10248           90 2021-07-04
1       10249           81 2021-07-05
2       10250           34 2021-07-08
3       10251           84 2021-07-08
4       10252           76 2021-07-09
..        ...          ...        ...
825     11073           58 2023-05-05
826     11074           73 2023-05-06
827     11075           68 2023-05-06
828     11076            9 2023-05-06
829     11077           65 2023-05-06

[830 rows x 3 columns]

In [17]:
#dataframe = pd.read_sql("SELECT * FROM customers", conn)
#dataframe = pd.read_sql("SELECT * FROM orders", conn)
#dataframe = pd.read_sql("SELECT * FROM products", conn)
dataframe = pd.read_sql_query("SELECT * FROM products", conn);

C:\Users\funka\AppData\Local\Temp\ipykernel_4540\520290235.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dataframe = pd.read_sql_query("SELECT * FROM products", conn);

In [48]:
dataframe

    product_id                      product_name  category_id                  unit   price
0            1                             Chais            1    10 boxes x 20 bags   18.00
1            2                             Chang            1    24 - 12 oz bottles   19.00
2            3                     Aniseed Syrup            2   12 - 550 ml bottles   10.00
3            4       Chef Antons Cajun Seasoning            2        48 - 6 oz jars   22.00
4            5             Chef Antons Gumbo Mix            2              36 boxes   21.35
5            6       Grandmas Boysenberry Spread            2        12 - 8 oz jars   25.00
6            7    Uncle Bobs Organic Dried Pears            7       12 - 1 lb pkgs.   30.00
7            8        Northwoods Cranberry Sauce            2       12 - 12 oz jars   40.00
8            9                   Mishi Kobe Niku            6      18 - 500 g pkgs.   97.00
9           10                             Ikura            8      12 - 200 ml jars   31.00
10          11                    Queso Cabrales            4             1 kg pkg.   21.00
11          12         Queso Manchego La Pastora            4      10 - 500 g pkgs.   38.00
12          13                             Konbu            8              2 kg box    6.00
13          14                              Tofu            7      40 - 100 g pkgs.   23.25
14          15                      Genen Shouyu            2   24 - 250 ml bottles   15.50
15          16                           Pavlova            3      32 - 500 g boxes   17.45
16          17                      Alice Mutton            6        20 - 1 kg tins   39.00
17          18                  Carnarvon Tigers            8            16 kg pkg.   62.50
18          19        Teatime Chocolate Biscuits            3  10 boxes x 12 pieces    9.20
19          20             Sir Rodneys Marmalade            3         30 gift boxes   81.00
20          21                Sir Rodneys Scones            3   24 pkgs. x 4 pieces   10.00
21          22                Gustafs Kneckebrod            5      24 - 500 g pkgs.   21.00
22          23                          Tunnbrod            5      12 - 250 g pkgs.    9.00
23          24                Guarani Fantastica            1      12 - 355 ml cans    4.50
24          25           NuNuCa Nui-Nougat-Creme            3    20 - 450 g glasses   14.00
25          26               Gumber Gummiberchen            3      100 - 250 g bags   31.23
26          27                Schoggi Schokolade            3    100 - 100 g pieces   43.90
27          28                 Rassle Sauerkraut            7       25 - 825 g cans   45.60
28          29           Thoringer Rostbratwurst            6  50 bags x 30 sausgs.  123.79
29          30             Nord-Ost Matjeshering            8    10 - 200 g glasses   25.89
30          31                 Gorgonzola Telino            4       12 - 100 g pkgs   12.50
31          32                Mascarpone Fabioli            4      24 - 200 g pkgs.   32.00
32          33                           Geitost            4                 500 g    2.50
33          34                     Sasquatch Ale            1    24 - 12 oz bottles   14.00
34          35                    Steeleye Stout            1    24 - 12 oz bottles   18.00
35          36                       Inlagd Sill            8       24 - 250 g jars   19.00
36          37                        Gravad lax            8      12 - 500 g pkgs.   26.00
37          38                     Cote de Blaye            1    12 - 75 cl bottles  263.50
38          39                  Chartreuse verte            1     750 cc per bottle   18.00
39          40                  Boston Crab Meat            8        24 - 4 oz tins   18.40
40          41    Jacks New England Clam Chowder            8       12 - 12 oz cans    9.65
41          42     Singaporean Hokkien Fried Mee            5       32 - 1 kg pkgs.   14.00
42          43                       Ipoh Coffee            1       16 - 500 g tins   46.00
43          44                      Gula Malacca            2        20 - 2 kg bags   19.45
44          45                       Rogede sild            8               1k pkg.    9.50
45          46                         Spegesild            8     4 - 450 g glasses   12.00
46          47                     Zaanse koeken            3       10 - 4 oz boxes    9.50
47          48                         Chocolade            3              10 pkgs.   12.75
48          49                          Maxilaku            3       24 - 50 g pkgs.   20.00
49          50                  Valkoinen suklaa            3       12 - 100 g bars   16.25
50          51             Manjimup Dried Apples            7      50 - 300 g pkgs.   53.00
51          52                          Filo Mix            5       16 - 2 kg boxes    7.00
52          53                     Perth Pasties            6             48 pieces   32.80
53          54                         Tourtiare            6               16 pies    7.45
54          55                      Pate chinois            6     24 boxes x 2 pies   24.00
55          56            Gnocchi di nonna Alice            5      24 - 250 g pkgs.   38.00
56          57                    Ravioli Angelo            5      24 - 250 g pkgs.   19.50
57          58            Escargots de Bourgogne            8             24 pieces   13.25
58          59              Raclette Courdavault            4             5 kg pkg.   55.00
59          60                 Camembert Pierrot            4     15 - 300 g rounds   34.00
60          61                    Sirop d arable            2   24 - 500 ml bottles   28.50
61          62                    Tarte au sucre            3               48 pies   49.30
62          63                      Vegie-spread            2       15 - 625 g jars   43.90
63          64         Wimmers gute Semmelknadel            5    20 bags x 4 pieces   33.25
64          65  Louisiana Fiery Hot Pepper Sauce            2     32 - 8 oz bottles   21.05
65          66         Louisiana Hot Spiced Okra            2        24 - 8 oz jars   17.00
66          67         Laughing Lumberjack Lager            1    24 - 12 oz bottles   14.00
67          68               Scottish Longbreads            3   10 boxes x 8 pieces   12.50
68          69                  Gudbrandsdalsost            4            10 kg pkg.   36.00
69          70                     Outback Lager            1   24 - 355 ml bottles   15.00
70          71                       Flotemysost            4      10 - 500 g pkgs.   21.50
71          72            Mozzarella di Giovanni            4      24 - 200 g pkgs.   34.80
72          73                        Red Kaviar            8       24 - 150 g jars   15.00
73          74                     Longlife Tofu            7             5 kg pkg.   10.00
74          75              Rhenbreu Klosterbier            1    24 - 0.5 l bottles    7.75
75          76                      Lakkalikeeri            1               500 ml    18.00
76          77   Original Frankfurter grőne Soae            2              12 boxes   13.00

In [19]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    77 non-null     int64
 1   product_name  77 non-null     object
 2   category_id   77 non-null     int64
 3   unit          77 non-null     object
 4   price         77 non-null     float64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.1+ KB

In [20]:
import psycopg2.extras

cur = conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor)
cur.execute('''SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog' AND 
    schemaname != 'information_schema';''')
res = cur.fetchall() 
print(res[0]['tablename'])

sekce

In [21]:
res

[RealDictRow([('schemaname', 'nace'),
              ('tablename', 'sekce'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', True),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)]),
 RealDictRow([('schemaname', 'nace'),
              ('tablename', 'skupiny'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', True),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)]),
 RealDictRow([('schemaname', 'nace'),
              ('tablename', 'tridy'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', True),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)]),
 RealDictRow([('schemaname', 'nace'),
              ('tablename', 'oddily'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', True),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)]),
 RealDictRow([('schemaname', 'nace'),
              ('tablename', 'sekce_podklad'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', True),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)]),
 RealDictRow([('schemaname', 'public'),
              ('tablename', 'categories'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', True),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)]),
 RealDictRow([('schemaname', 'public'),
              ('tablename', 'customers'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', True),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)]),
 RealDictRow([('schemaname', 'public'),
              ('tablename', 'products'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', True),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)]),
 RealDictRow([('schemaname', 'public'),
              ('tablename', 'orders'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', True),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)]),
 RealDictRow([('schemaname', 'public'),
              ('tablename', 'order_details'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', True),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)]),
 RealDictRow([('schemaname', 'public'),
              ('tablename', 'testproducts'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', True),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)]),
 RealDictRow([('schemaname', 'public'),
              ('tablename', 'bill2'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', False),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)]),
 RealDictRow([('schemaname', 'public'),
              ('tablename', 'bill'),
              ('tableowner', 'funka'),
              ('tablespace', None),
              ('hasindexes', False),
              ('hasrules', False),
              ('hastriggers', False),
              ('rowsecurity', False)])]

In [28]:
cur.execute('select * from aaa');

UndefinedTable: relation "aaa" does not exist
LINE 1: select * from aaa
                      ^

In [30]:
#po chybe musit udelat toto jinak nelze pokracovat
curs = conn.cursor()
curs.execute("ROLLBACK")
conn.commit()

In [31]:
cur.execute('select * from nace.sekce');

In [32]:
res = cur.fetchall() 
res

[RealDictRow([('id', 1),
              ('kod', 'A'),
              ('nazev', 'SEKCE A - ZEMĚDĚLSTVÍ, LESNICTVÍ A\xa0RYBÁŘSTVÍ')]),
 RealDictRow([('id', 2),
              ('kod', 'B'),
              ('nazev', 'SEKCE B - TĚŽBA A DOBÝVÁNÍ')]),
 RealDictRow([('id', 3),
              ('kod', 'C'),
              ('nazev', 'SEKCE C - ZPRACOVATELSKÝ PRŮMYSL')]),
 RealDictRow([('id', 4),
              ('kod', 'D'),
              ('nazev',
               'SEKCE D – VÝROBA A ROZVOD ELEKTŘINY, PLYNU, TEPLA A\xa0KLIMATIZOVANÉHO VZDUCHU')]),
 RealDictRow([('id', 5),
              ('kod', 'E'),
              ('nazev',
               'SEKCE E – ZÁSOBOVÁNÍ VODOU; ČINNOSTI SOUVISEJÍCÍ S\xa0ODPADNÍMI VODAMI, ODPADY A SANACEMI')]),
 RealDictRow([('id', 6), ('kod', 'F'), ('nazev', 'SEKCE F - STAVEBNICTVÍ')]),
 RealDictRow([('id', 7),
              ('kod', 'G'),
              ('nazev',
               'SEKCE G - VELKOOBCHOD A MALOOBCHOD; OPRAVY A\xa0ÚDRŽBA MOTOROVÝCH VOZIDEL')]),
 RealDictRow([('id', 8),
              ('kod', 'H'),
              ('nazev', 'SEKCE H - DOPRAVA A SKLADOVÁNÍ')]),
 RealDictRow([('id', 9),
              ('kod', 'I'),
              ('nazev', 'SEKCE I - UBYTOVÁNÍ, STRAVOVÁNÍ A\xa0POHOSTINSTVÍ')]),
 RealDictRow([('id', 10),
              ('kod', 'J'),
              ('nazev', 'SEKCE J - INFORMAČNÍ A KOMUNIKAČNÍ ČINNOSTI')]),
 RealDictRow([('id', 11),
              ('kod', 'K'),
              ('nazev', 'SEKCE K - PENĚŽNICTVÍ A POJIŠŤOVNICTVÍ')]),
 RealDictRow([('id', 12),
              ('kod', 'L'),
              ('nazev', 'SEKCE L - ČINNOSTI V\xa0OBLASTI NEMOVITOSTÍ')]),
 RealDictRow([('id', 13),
              ('kod', 'M'),
              ('nazev',
               'SEKCE M - PROFESNÍ, VĚDECKÉ A\xa0TECHNICKÉ ČINNOSTI')]),
 RealDictRow([('id', 14),
              ('kod', 'N'),
              ('nazev', 'SEKCE N - ADMINISTRATIVNÍ A PODPŮRNÉ ČINNOSTI')]),
 RealDictRow([('id', 15),
              ('kod', 'O'),
              ('nazev',
               'SEKCE O - VEŘEJNÁ SPRÁVA A OBRANA; POVINNÉ SOCIÁLNÍ ZABEZPEČENÍ')]),
 RealDictRow([('id', 16), ('kod', 'P'), ('nazev', 'SEKCE P – VZDĚLÁVÁNÍ')]),
 RealDictRow([('id', 17),
              ('kod', 'Q'),
              ('nazev', 'SEKCE Q - ZDRAVOTNÍ A SOCIÁLNÍ PÉČE')]),
 RealDictRow([('id', 18),
              ('kod', 'R'),
              ('nazev',
               'SEKCE R - KULTURNÍ, ZÁBAVNÍ A\xa0REKREAČNÍ ČINNOSTI')]),
 RealDictRow([('id', 19),
              ('kod', 'S'),
              ('nazev', 'SEKCE S - OSTATNÍ ČINNOSTI')]),
 RealDictRow([('id', 20),
              ('kod', 'T'),
              ('nazev',
               'SEKCE T - ČINNOSTI DOMÁCNOSTÍ JAKO\xa0ZAMĚSTNAVATELŮ; ČINNOSTI DOMÁCNOSTÍ PRODUKUJÍCÍCH BLÍŽE NEURČENÉ VÝROBKY A SLUŽBY PRO\xa0VLASTNÍ POTŘEBU')]),
 RealDictRow([('id', 21),
              ('kod', 'U'),
              ('nazev',
               'SEKCE U - ČINNOSTI EXTERITORIÁLNÍCH ORGANIZACÍ A\xa0ORGÁNŮ')])]

In [35]:
res = pd.read_sql_query('''select * from nace.sekce ''', con = conn)

C:\Users\funka\AppData\Local\Temp\ipykernel_4540\61982907.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  res = pd.read_sql_query('''select * from nace.sekce ''', con = conn)

In [46]:
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999
pd.options.display.max_colwidth = 999

In [47]:
res

    id kod                                                                                                                                     nazev
0    1   A                                                                                              SEKCE A - ZEMĚDĚLSTVÍ, LESNICTVÍ A RYBÁŘSTVÍ
1    2   B                                                                                                                SEKCE B - TĚŽBA A DOBÝVÁNÍ
2    3   C                                                                                                          SEKCE C - ZPRACOVATELSKÝ PRŮMYSL
3    4   D                                                               SEKCE D – VÝROBA A ROZVOD ELEKTŘINY, PLYNU, TEPLA A KLIMATIZOVANÉHO VZDUCHU
4    5   E                                                    SEKCE E – ZÁSOBOVÁNÍ VODOU; ČINNOSTI SOUVISEJÍCÍ S ODPADNÍMI VODAMI, ODPADY A SANACEMI
5    6   F                                                                                                                    SEKCE F - STAVEBNICTVÍ
6    7   G                                                                    SEKCE G - VELKOOBCHOD A MALOOBCHOD; OPRAVY A ÚDRŽBA MOTOROVÝCH VOZIDEL
7    8   H                                                                                                            SEKCE H - DOPRAVA A SKLADOVÁNÍ
8    9   I                                                                                            SEKCE I - UBYTOVÁNÍ, STRAVOVÁNÍ A POHOSTINSTVÍ
9   10   J                                                                                               SEKCE J - INFORMAČNÍ A KOMUNIKAČNÍ ČINNOSTI
10  11   K                                                                                                    SEKCE K - PENĚŽNICTVÍ A POJIŠŤOVNICTVÍ
11  12   L                                                                                                  SEKCE L - ČINNOSTI V OBLASTI NEMOVITOSTÍ
12  13   M                                                                                          SEKCE M - PROFESNÍ, VĚDECKÉ A TECHNICKÉ ČINNOSTI
13  14   N                                                                                             SEKCE N - ADMINISTRATIVNÍ A PODPŮRNÉ ČINNOSTI
14  15   O                                                                           SEKCE O - VEŘEJNÁ SPRÁVA A OBRANA; POVINNÉ SOCIÁLNÍ ZABEZPEČENÍ
15  16   P                                                                                                                      SEKCE P – VZDĚLÁVÁNÍ
16  17   Q                                                                                                       SEKCE Q - ZDRAVOTNÍ A SOCIÁLNÍ PÉČE
17  18   R                                                                                          SEKCE R - KULTURNÍ, ZÁBAVNÍ A REKREAČNÍ ČINNOSTI
18  19   S                                                                                                                SEKCE S - OSTATNÍ ČINNOSTI
19  20   T  SEKCE T - ČINNOSTI DOMÁCNOSTÍ JAKO ZAMĚSTNAVATELŮ; ČINNOSTI DOMÁCNOSTÍ PRODUKUJÍCÍCH BLÍŽE NEURČENÉ VÝROBKY A SLUŽBY PRO VLASTNÍ POTŘEBU
20  21   U                                                                                   SEKCE U - ČINNOSTI EXTERITORIÁLNÍCH ORGANIZACÍ A ORGÁNŮ

In [52]:
print(res.loc[20, 'nazev'])

SEKCE U - ČINNOSTI EXTERITORIÁLNÍCH ORGANIZACÍ A ORGÁNŮ