In [7]:
import psycopg2

In [8]:
# Connect to your postgres DB
conn = psycopg2.connect("dbname=test user=funka password=funka")

In [9]:
# Open a cursor to perform database operations
cur = conn.cursor()

There are two wildcards often used in conjunction with the LIKE operator:
- '%' The percent sign represents zero, one, or multiple characters
- '_' The underscore sign represents one, single character

Return all customers with a name that starts with the letter 'A':

In [16]:
# Execute a query
cur.execute('''SELECT * FROM customers
WHERE customer_name LIKE 'A%';''')

In [17]:
# Retrieve query results
records = cur.fetchall()

In [18]:
records

[(1,
  'Alfreds Futterkiste',
  'Maria Anders',
  'Obere Str. 57',
  'Berlin',
  '12209',
  'Germany'),
 (2,
  'Ana Trujillo Emparedados y helados',
  'Ana Trujillo',
  'Avda. de la Constitucion 2222',
  'Mexico D.F.',
  '05021',
  'Mexico'),
 (3,
  'Antonio Moreno Taquera',
  'Antonio Moreno',
  'Mataderos 2312',
  'Mexico D.F.',
  '05023',
  'Mexico'),
 (4,
  'Around the Horn',
  'Thomas Hardy',
  '120 Hanover Sq.',
  'London',
  'WA1 1DP',
  'UK')]

Return all customers with a name that contains the letter 'A':

In [19]:
# Execute a query
cur.execute('''SELECT * FROM customers
WHERE customer_name LIKE '%A%';''')

In [20]:
# Retrieve query results
records = cur.fetchall()

In [21]:
records

[(1,
  'Alfreds Futterkiste',
  'Maria Anders',
  'Obere Str. 57',
  'Berlin',
  '12209',
  'Germany'),
 (2,
  'Ana Trujillo Emparedados y helados',
  'Ana Trujillo',
  'Avda. de la Constitucion 2222',
  'Mexico D.F.',
  '05021',
  'Mexico'),
 (3,
  'Antonio Moreno Taquera',
  'Antonio Moreno',
  'Mataderos 2312',
  'Mexico D.F.',
  '05023',
  'Mexico'),
 (4,
  'Around the Horn',
  'Thomas Hardy',
  '120 Hanover Sq.',
  'London',
  'WA1 1DP',
  'UK'),
 (21,
  'Familia Arquibaldo',
  'Aria Cruz',
  'Rua Oros, 92',
  'Sao Paulo',
  '05442-030',
  'Brazil'),
 (22,
  'FISSA Fabrica Inter. Salchichas S.A.',
  'Diego Roel',
  'C/ Moralzarzal, 86',
  'Madrid',
  '28034',
  'Spain'),
 (27,
  'Franchi S.p.A.',
  'Paolo Accorti',
  'Via Monte Bianco 34',
  'Torino',
  '10100',
  'Italy'),
 (33,
  'GROSELLA-Restaurante',
  'Manuel Pereira',
  '5th Ave. Los Palos Grandes',
  'Caracas',
  '1081',
  'Venezuela'),
 (35,
  'HILARION-Abastos',
  'Carlos Hernandez',
  'Carrera 22 con Ave. Carlos Soublette #8-35',
  'San Cristobal',
  '5022',
  'Venezuela'),
 (37,
  'Hungry Owl All-Night Grocers',
  'Patricia McKenna',
  '8 Johnstown Road',
  'Cork',
  '',
  'Ireland'),
 (41,
  'La maison d Asie',
  'Annette Roulet',
  '1 rue Alsace-Lorraine',
  'Toulouse',
  '31000',
  'France'),
 (46,
  'LILA-Supermercado',
  'Carlos Gonzalez',
  'Carrera 52 con Ave. Bolivar #65-98 Llano Largo',
  'Barquisimeto',
  '3508',
  'Venezuela'),
 (49,
  'Magazzini Alimentari Riuniti',
  'Giovanni Rovelli',
  'Via Ludovico il Moro 22',
  'Bergamo',
  '24100',
  'Italy'),
 (54,
  'Oceano Atlantico Ltda.',
  'Yvonne Moncada',
  'Ing. Gustavo Moncada 8585 Piso 20-A',
  'Buenos Aires',
  '1010',
  'Argentina'),
 (67,
  'Ricardo Adocicados',
  'Janete Limeira',
  'Av. Copacabana, 267',
  'Rio de Janeiro',
  '02389-890',
  'Brazil'),
 (75,
  'Split Rail Beer & Ale',
  'Art Braunschweiger',
  'P.O. Box 555',
  'Lander',
  '82520',
  'USA')]

Return all customers with a name that ends with the phrase 'en':

In [22]:
# Execute a query
cur.execute('''SELECT * FROM customers
WHERE customer_name LIKE '%en';''')

In [23]:
# Retrieve query results
records = cur.fetchall()

In [24]:
records

[(6,
  'Blauer See Delikatessen',
  'Hanna Moos',
  'Forsterstr. 57',
  'Mannheim',
  '68306',
  'Germany'),
 (39,
  'Koniglich Essen',
  'Philip Cramer',
  'Maubelstr. 90',
  'Brandenburg',
  '14776',
  'Germany'),
 (55,
  'Old World Delicatessen',
  'Rene Phillips',
  '2743 Bering St.',
  'Anchorage',
  '99508',
  'USA'),
 (56,
  'Ottilies Keseladen',
  'Henriette Pfalzheim',
  'Mehrheimerstr. 369',
  'Koln',
  '50739',
  'Germany'),
 (79,
  'Toms Spezialiteten',
  'Karin Josephs',
  'Luisenstr. 48',
  'Manster',
  '44087',
  'Germany')]

Return all customers from a city that starts with 'L' followed by one wildcard character, then 'nd' and then two wildcard characters:

In [25]:
# Execute a query
cur.execute('''SELECT * FROM customers
WHERE city LIKE 'L_nd__';''')

In [26]:
# Retrieve query results
records = cur.fetchall()

In [27]:
records

[(4,
  'Around the Horn',
  'Thomas Hardy',
  '120 Hanover Sq.',
  'London',
  'WA1 1DP',
  'UK'),
 (11,
  'Bs Beverages',
  'Victoria Ashworth',
  'Fauntleroy Circus',
  'London',
  'EC2 5NT',
  'UK'),
 (16,
  'Consolidated Holdings',
  'Elizabeth Brown',
  'Berkeley Gardens 12 Brewery ',
  'London',
  'WX1 6LT',
  'UK'),
 (19,
  'Eastern Connection',
  'Ann Devon',
  '35 King George',
  'London',
  'WX3 6FW',
  'UK'),
 (53,
  'North/South',
  'Simon Crowther',
  'South House 300 Queensbridge',
  'London',
  'SW7 1RZ',
  'UK'),
 (72,
  'Seven Seas Imports',
  'Hari Kumar',
  '90 Wadhurst Rd.',
  'London',
  'OX15 4NB',
  'UK'),
 (75,
  'Split Rail Beer & Ale',
  'Art Braunschweiger',
  'P.O. Box 555',
  'Lander',
  '82520',
  'USA')]

Note: The LIKE operator is case sensitive, if you want to do a case insensitive search, use the ILIKE operator instead.

Return all customers with a name that contains the letter 'A' or 'a':

In [28]:
# Execute a query
cur.execute('''SELECT * FROM customers
WHERE customer_name ILIKE '%A%';''')

In [29]:
# Retrieve query results
records = cur.fetchall()

In [30]:
records

[(1,
  'Alfreds Futterkiste',
  'Maria Anders',
  'Obere Str. 57',
  'Berlin',
  '12209',
  'Germany'),
 (2,
  'Ana Trujillo Emparedados y helados',
  'Ana Trujillo',
  'Avda. de la Constitucion 2222',
  'Mexico D.F.',
  '05021',
  'Mexico'),
 (3,
  'Antonio Moreno Taquera',
  'Antonio Moreno',
  'Mataderos 2312',
  'Mexico D.F.',
  '05023',
  'Mexico'),
 (4,
  'Around the Horn',
  'Thomas Hardy',
  '120 Hanover Sq.',
  'London',
  'WA1 1DP',
  'UK'),
 (5,
  'Berglunds snabbkoep',
  'Christina Berglund',
  'Berguvsvegen 8',
  'Lulea',
  'S-958 22',
  'Sweden'),
 (6,
  'Blauer See Delikatessen',
  'Hanna Moos',
  'Forsterstr. 57',
  'Mannheim',
  '68306',
  'Germany'),
 (8,
  'Bolido Comidas preparadas',
  'Martin Sommer',
  'C/ Araquil, 67',
  'Madrid',
  '28023',
  'Spain'),
 (9,
  'Bon app',
  'Laurence Lebihans',
  '12, rue des Bouchers',
  'Marseille',
  '13008',
  'France'),
 (10,
  'Bottom-Dollar Marketse',
  'Elizabeth Lincoln',
  '23 Tsawassen Blvd.',
  'Tsawassen',
  'T2F 8M4',
  'Canada'),
 (11,
  'Bs Beverages',
  'Victoria Ashworth',
  'Fauntleroy Circus',
  'London',
  'EC2 5NT',
  'UK'),
 (12,
  'Cactus Comidas para llevar',
  'Patricio Simpson',
  'Cerrito 333',
  'Buenos Aires',
  '1010',
  'Argentina'),
 (13,
  'Centro comercial Moctezuma',
  'Francisco Chang',
  'Sierras de Granada 9993',
  'Mexico D.F.',
  '05022',
  'Mexico'),
 (16,
  'Consolidated Holdings',
  'Elizabeth Brown',
  'Berkeley Gardens 12 Brewery ',
  'London',
  'WX1 6LT',
  'UK'),
 (17,
  'Drachenblut Delikatessend',
  'Sven Ottlieb',
  'Walserweg 21',
  'Aachen',
  '52066',
  'Germany'),
 (19,
  'Eastern Connection',
  'Ann Devon',
  '35 King George',
  'London',
  'WX3 6FW',
  'UK'),
 (20,
  'Ernst Handel',
  'Roland Mendel',
  'Kirchgasse 6',
  'Graz',
  '8010',
  'Austria'),
 (21,
  'Familia Arquibaldo',
  'Aria Cruz',
  'Rua Oros, 92',
  'Sao Paulo',
  '05442-030',
  'Brazil'),
 (22,
  'FISSA Fabrica Inter. Salchichas S.A.',
  'Diego Roel',
  'C/ Moralzarzal, 86',
  'Madrid',
  '28034',
  'Spain'),
 (23,
  'Folies gourmandes',
  'Martine Rance',
  '184, chaussee de Tournai',
  'Lille',
  '59000',
  'France'),
 (25,
  'Frankenversand',
  'Peter Franken',
  'Berliner Platz 43',
  'Munchen',
  '80805',
  'Germany'),
 (26,
  'France restauration',
  'Carine Schmitt',
  '54, rue Royale',
  'Nantes',
  '44000',
  'France'),
 (27,
  'Franchi S.p.A.',
  'Paolo Accorti',
  'Via Monte Bianco 34',
  'Torino',
  '10100',
  'Italy'),
 (28,
  'Furia Bacalhau e Frutos do Mar',
  'Lino Rodriguez ',
  'Jardim das rosas n. 32',
  'Lisboa',
  '1675',
  'Portugal'),
 (29,
  'Galeria del gastronomo',
  'Eduardo Saavedra',
  'Rambla de Cataluna, 23',
  'Barcelona',
  '08022',
  'Spain'),
 (30,
  'Godos Cocina Tipica',
  'Jose Pedro Freyre',
  'C/ Romero, 33',
  'Sevilla',
  '41101',
  'Spain'),
 (31,
  'Gourmet Lanchonetes',
  'Andre Fonseca',
  'Av. Brasil, 442',
  'Campinas',
  '04876-786',
  'Brazil'),
 (32,
  'Great Lakes Food Market',
  'Howard Snyder',
  '2732 Baker Blvd.',
  'Eugene',
  '97403',
  'USA'),
 (33,
  'GROSELLA-Restaurante',
  'Manuel Pereira',
  '5th Ave. Los Palos Grandes',
  'Caracas',
  '1081',
  'Venezuela'),
 (34,
  'Hanari Carnes',
  'Mario Pontes',
  'Rua do Paco, 67',
  'Rio de Janeiro',
  '05454-876',
  'Brazil'),
 (35,
  'HILARION-Abastos',
  'Carlos Hernandez',
  'Carrera 22 con Ave. Carlos Soublette #8-35',
  'San Cristobal',
  '5022',
  'Venezuela'),
 (37,
  'Hungry Owl All-Night Grocers',
  'Patricia McKenna',
  '8 Johnstown Road',
  'Cork',
  '',
  'Ireland'),
 (38,
  'Island Trading',
  'Helen Bennett',
  'Garden House Crowther Way',
  'Cowes',
  'PO31 7PJ',
  'UK'),
 (40,
  'La corne d abondance',
  'Daniel Tonini',
  '67, avenue de l Europe',
  'Versailles',
  '78000',
  'France'),
 (41,
  'La maison d Asie',
  'Annette Roulet',
  '1 rue Alsace-Lorraine',
  'Toulouse',
  '31000',
  'France'),
 (42,
  'Laughing Bacchus Wine Cellars',
  'Yoshi Tannamuri',
  '1900 Oak St.',
  'Vancouver',
  'V3F 2K1',
  'Canada'),
 (43,
  'Lazy K Kountry Store',
  'John Steel',
  '12 Orchestra Terrace',
  'Walla Walla',
  '99362',
  'USA'),
 (44,
  'Lehmanns Marktstand',
  'Renate Messner',
  'Magazinweg 7',
  'Frankfurt a.M. ',
  '60528',
  'Germany'),
 (46,
  'LILA-Supermercado',
  'Carlos Gonzalez',
  'Carrera 52 con Ave. Bolivar #65-98 Llano Largo',
  'Barquisimeto',
  '3508',
  'Venezuela'),
 (47,
  'LINO-Delicateses',
  'Felipe Izquierdo',
  'Ave. 5 de Mayo Porlamar',
  'I. de Margarita',
  '4980',
  'Venezuela'),
 (48,
  'Lonesome Pine Restaurant',
  'Fran Wilson',
  '89 Chiaroscuro Rd.',
  'Portland',
  '97219',
  'USA'),
 (49,
  'Magazzini Alimentari Riuniti',
  'Giovanni Rovelli',
  'Via Ludovico il Moro 22',
  'Bergamo',
  '24100',
  'Italy'),
 (50,
  'Maison Dewey',
  'Catherine Dewey',
  'Rue Joseph-Bens 532',
  'Bruxelles',
  'B-1180',
  'Belgium'),
 (51,
  'Mere Paillarde',
  'Jean Fresniere',
  '43 rue St. Laurent',
  'Montreal',
  'H1J 1C3',
  'Canada'),
 (54,
  'Oceano Atlantico Ltda.',
  'Yvonne Moncada',
  'Ing. Gustavo Moncada 8585 Piso 20-A',
  'Buenos Aires',
  '1010',
  'Argentina'),
 (55,
  'Old World Delicatessen',
  'Rene Phillips',
  '2743 Bering St.',
  'Anchorage',
  '99508',
  'USA'),
 (56,
  'Ottilies Keseladen',
  'Henriette Pfalzheim',
  'Mehrheimerstr. 369',
  'Koln',
  '50739',
  'Germany'),
 (57,
  'Paris specialites',
  'Marie Bertrand',
  '265, boulevard Charonne',
  'Paris',
  '75012',
  'France'),
 (58,
  'Pericles Comidas clasicas',
  'Guillermo Fernandez',
  'Calle Dr. Jorge Cash 321',
  'Mexico D.F.',
  '05033',
  'Mexico'),
 (60,
  'Princesa Isabel Vinhoss',
  'Isabel de Castro',
  'Estrada da saude n. 58',
  'Lisboa',
  '1756',
  'Portugal'),
 (61,
  'Que Delicia',
  'Bernardo Batista',
  'Rua da Panificadora, 12',
  'Rio de Janeiro',
  '02389-673',
  'Brazil'),
 (62,
  'Queen Cozinha',
  'Lucia Carvalho',
  'Alameda dos Canarios, 891',
  'Sao Paulo',
  '05487-020',
  'Brazil'),
 (64,
  'Rancho grande',
  'Sergio Gutiarrez',
  'Av. del Libertador 900',
  'Buenos Aires',
  '1010',
  'Argentina'),
 (65,
  'Rattlesnake Canyon Grocery',
  'Paula Wilson',
  '2817 Milton Dr.',
  'Albuquerque',
  '87110',
  'USA'),
 (66,
  'Reggiani Caseifici',
  'Maurizio Moroni',
  'Strada Provinciale 124',
  'Reggio Emilia',
  '42100',
  'Italy'),
 (67,
  'Ricardo Adocicados',
  'Janete Limeira',
  'Av. Copacabana, 267',
  'Rio de Janeiro',
  '02389-890',
  'Brazil'),
 (68,
  'Richter Supermarkt',
  'Michael Holz',
  'Grenzacherweg 237',
  'Genève',
  '1203',
  'Switzerland'),
 (70,
  'Santa Gourmet',
  'Jonas Bergulfsen',
  'Erling Skakkes gate 78',
  'Stavern',
  '4110',
  'Norway'),
 (71,
  'Save-a-lot Markets',
  'Jose Pavarotti',
  '187 Suffolk Ln.',
  'Boise',
  '83720',
  'USA'),
 (72,
  'Seven Seas Imports',
  'Hari Kumar',
  '90 Wadhurst Rd.',
  'London',
  'OX15 4NB',
  'UK'),
 (74,
  'Specialites du monde',
  'Dominique Perrier',
  '25, rue Lauriston',
  'Paris',
  '75016',
  'France'),
 (75,
  'Split Rail Beer & Ale',
  'Art Braunschweiger',
  'P.O. Box 555',
  'Lander',
  '82520',
  'USA'),
 (78,
  'The Cracker Box',
  'Liu Wong',
  '55 Grizzly Peak Rd.',
  'Butte',
  '59801',
  'USA'),
 (79,
  'Toms Spezialiteten',
  'Karin Josephs',
  'Luisenstr. 48',
  'Manster',
  '44087',
  'Germany'),
 (80,
  'Tortuga Restaurante',
  'Miguel Angel Paolino',
  'Avda. Azteca 123',
  'Mexico D.F.',
  '05033',
  'Mexico'),
 (81,
  'Tradicao Hipermercados',
  'Anabela Domingues',
  'Av. Ines de Castro, 414',
  'Sao Paulo',
  '05634-030',
  'Brazil'),
 (82,
  'Trails Head Gourmet Provisioners',
  'Helvetius Nagy',
  '722 DaVinci Blvd.',
  'Kirkland',
  '98034',
  'USA'),
 (83,
  'Vaffeljernet',
  'Palle Ibsen',
  'Smagsloget 45',
  'Arhus',
  '8200',
  'Denmark'),
 (84,
  'Victuailles en stock',
  'Mary Saveley',
  '2, rue du Commerce',
  'Lyon',
  '69004',
  'France'),
 (85,
  'Vins et alcools Chevalier',
  'Paul Henriot',
  '59 rue de l Abbaye',
  'Reims',
  '51100',
  'France'),
 (86,
  'Die Wandernde Kuh',
  'Rita Moller',
  'Adenauerallee 900',
  'Stuttgart',
  '70563',
  'Germany'),
 (87,
  'Wartian Herkku',
  'Pirkko Koskitalo',
  'Torikatu 38',
  'Oulu',
  '90110',
  'Finland'),
 (88,
  'Wellington Importadora',
  'Paula Parente',
  'Rua do Mercado, 12',
  'Resende',
  '08737-363',
  'Brazil'),
 (89,
  'White Clover Markets',
  'Karl Jablonski',
  '305 - 14th Ave. S. Suite 3B',
  'Seattle',
  '98128',
  'USA'),
 (90,
  'Wilman Kala',
  'Matti Karttunen',
  'Keskuskatu 45',
  'Helsinki',
  '21240',
  'Finland')]