In [1]:
from MySQLdb import connect

In [2]:
conn = connect(host='localhost', user='root')

In [3]:
cur = conn.cursor()

In [4]:
cur.execute('show schemas;')

5

In [5]:
result = cur.fetchall();

In [6]:
result

(('information_schema',),
 ('mysql',),
 ('performance_schema',),
 ('sqlw3s',),
 ('sys',))

In [7]:
cur.execute('create table if not exists sqlw3s.Customers (CustomerID int, CustomerName varchar(255), ContactName varchar(255), Address varchar(255), City varchar(255), PostalCode varchar(255), Country varchar(255));')

0

In [8]:
conn.commit()

In [9]:
cur.execute('select * from sqlw3s.Customers;')
result = cur.fetchall();
result

()

In [10]:
pwd

'c:\\_venv\\_jupyter\\W3Schools_2024\\SQL'

In [11]:
rows = []
with open('_data\Customers.txt', encoding = 'utf-8') as f:
    line = f.readline()
    while line:
        #print(line)
        columns = line.split('\t')
        for i, column in enumerate(columns):
            columns[i] = column.strip()
        rows.append(columns)
        line = f.readline()

<>:2: SyntaxWarning: invalid escape sequence '\C'
<>:2: SyntaxWarning: invalid escape sequence '\C'
C:\Users\funka\AppData\Local\Temp\ipykernel_3092\3088874792.py:2: SyntaxWarning: invalid escape sequence '\C'
  with open('_data\Customers.txt', encoding = 'utf-8') as f:

In [12]:
rows

[['CustomerID',
  'CustomerName',
  'ContactName',
  'Address',
  'City',
  'PostalCode',
  'Country'],
 ['1',
  'Alfreds Futterkiste',
  'Maria Anders',
  'Obere Str. 57',
  'Berlin',
  '12209',
  'Germany'],
 ['2',
  'Ana Trujillo Emparedados y helados',
  'Ana Trujillo',
  'Avda. de la Constitución 2222',
  'México D.F.',
  '05021',
  'Mexico'],
 ['3',
  'Antonio Moreno Taquería',
  'Antonio Moreno',
  'Mataderos 2312',
  'México D.F.',
  '05023',
  'Mexico'],
 ['4',
  'Around the Horn',
  'Thomas Hardy',
  '120 Hanover Sq.',
  'London',
  'WA1 1DP',
  'UK'],
 ['5',
  'Berglunds snabbköp',
  'Christina Berglund',
  'Berguvsvägen 8',
  'Luleå',
  'S-958 22',
  'Sweden'],
 ['6',
  'Blauer See Delikatessen',
  'Hanna Moos',
  'Forsterstr. 57',
  'Mannheim',
  '68306',
  'Germany'],
 ['7',
  'Blondel père et fils',
  'Frédérique Citeaux',
  '24, place Kléber',
  'Strasbourg',
  '67000',
  'France'],
 ['8',
  'Bólido Comidas preparadas',
  'Martín Sommer',
  'C/ Araquil, 67',
  'Madrid',
  '28023',
  'Spain'],
 ['9',
  "Bon app'",
  'Laurence Lebihans',
  '12, rue des Bouchers',
  'Marseille',
  '13008',
  'France'],
 ['10',
  'Bottom-Dollar Marketse',
  'Elizabeth Lincoln',
  '23 Tsawassen Blvd.',
  'Tsawassen',
  'T2F 8M4',
  'Canada'],
 ['11',
  "B's Beverages",
  'Victoria Ashworth',
  'Fauntleroy Circus',
  'London',
  'EC2 5NT',
  'UK'],
 ['12',
  'Cactus Comidas para llevar',
  'Patricio Simpson',
  'Cerrito 333',
  'Buenos Aires',
  '1010',
  'Argentina'],
 ['13',
  'Centro comercial Moctezuma',
  'Francisco Chang',
  'Sierras de Granada 9993',
  'México D.F.',
  '05022',
  'Mexico'],
 ['14',
  'Chop-suey Chinese',
  'Yang Wang',
  'Hauptstr. 29',
  'Bern',
  '3012',
  'Switzerland'],
 ['15',
  'Comércio Mineiro',
  'Pedro Afonso',
  'Av. dos Lusíadas, 23',
  'São Paulo',
  '05432-043',
  'Brazil'],
 ['16',
  'Consolidated Holdings',
  'Elizabeth Brown',
  'Berkeley Gardens 12 Brewery',
  'London',
  'WX1 6LT',
  'UK'],
 ['17',
  'Drachenblut Delikatessend',
  'Sven Ottlieb',
  'Walserweg 21',
  'Aachen',
  '52066',
  'Germany'],
 ['18',
  'Du monde entier',
  'Janine Labrune',
  '67, rue des Cinquante Otages',
  'Nantes',
  '44000',
  'France'],
 ['19',
  'Eastern Connection',
  'Ann Devon',
  '35 King George',
  'London',
  'WX3 6FW',
  'UK'],
 ['20',
  'Ernst Handel',
  'Roland Mendel',
  'Kirchgasse 6',
  'Graz',
  '8010',
  'Austria'],
 ['21',
  'Familia Arquibaldo',
  'Aria Cruz',
  'Rua Orós, 92',
  'São Paulo',
  '05442-030',
  'Brazil'],
 ['22',
  'FISSA Fabrica Inter. Salchichas S.A.',
  'Diego Roel',
  'C/ Moralzarzal, 86',
  'Madrid',
  '28034',
  'Spain'],
 ['23',
  'Folies gourmandes',
  'Martine Rancé',
  '184, chaussée de Tournai',
  'Lille',
  '59000',
  'France'],
 ['24',
  'Folk och fä HB',
  'Maria Larsson',
  'Åkergatan 24',
  'Bräcke',
  'S-844 67',
  'Sweden'],
 ['25',
  'Frankenversand',
  'Peter Franken',
  'Berliner Platz 43',
  'München',
  '80805',
  'Germany'],
 ['26',
  'France restauration',
  'Carine Schmitt',
  '54, rue Royale',
  'Nantes',
  '44000',
  'France'],
 ['27',
  'Franchi S.p.A.',
  'Paolo Accorti',
  'Via Monte Bianco 34',
  'Torino',
  '10100',
  'Italy'],
 ['28',
  'Furia Bacalhau e Frutos do Mar',
  'Lino Rodriguez',
  'Jardim das rosas n. 32',
  'Lisboa',
  '1675',
  'Portugal'],
 ['29',
  'Galería del gastrónomo',
  'Eduardo Saavedra',
  'Rambla de Cataluña, 23',
  'Barcelona',
  '08022',
  'Spain'],
 ['30',
  'Godos Cocina Típica',
  'José Pedro Freyre',
  'C/ Romero, 33',
  'Sevilla',
  '41101',
  'Spain'],
 ['31',
  'Gourmet Lanchonetes',
  'André Fonseca',
  'Av. Brasil, 442',
  'Campinas',
  '04876-786',
  'Brazil'],
 ['32',
  'Great Lakes Food Market',
  'Howard Snyder',
  '2732 Baker Blvd.',
  'Eugene',
  '97403',
  'USA'],
 ['33',
  'GROSELLA-Restaurante',
  'Manuel Pereira',
  '5ª Ave. Los Palos Grandes',
  'Caracas',
  '1081',
  'Venezuela'],
 ['34',
  'Hanari Carnes',
  'Mario Pontes',
  'Rua do Paço, 67',
  'Rio de Janeiro',
  '05454-876',
  'Brazil'],
 ['35',
  'HILARIÓN-Abastos',
  'Carlos Hernández',
  'Carrera 22 con Ave. Carlos Soublette #8-35',
  'San Cristóbal',
  '5022',
  'Venezuela'],
 ['36',
  'Hungry Coyote Import Store',
  'Yoshi Latimer',
  'City Center Plaza 516 Main St.',
  'Elgin',
  '97827',
  'USA'],
 ['37',
  'Hungry Owl All-Night Grocers',
  'Patricia McKenna',
  '8 Johnstown Road',
  'Cork',
  '',
  'Ireland'],
 ['38',
  'Island Trading',
  'Helen Bennett',
  'Garden House Crowther Way',
  'Cowes',
  'PO31 7PJ',
  'UK'],
 ['39',
  'Königlich Essen',
  'Philip Cramer',
  'Maubelstr. 90',
  'Brandenburg',
  '14776',
  'Germany'],
 ['40',
  "La corne d'abondance",
  'Daniel Tonini',
  "67, avenue de l'Europe",
  'Versailles',
  '78000',
  'France'],
 ['41',
  "La maison d'Asie",
  'Annette Roulet',
  '1 rue Alsace-Lorraine',
  'Toulouse',
  '31000',
  'France'],
 ['42',
  'Laughing Bacchus Wine Cellars',
  'Yoshi Tannamuri',
  '1900 Oak St.',
  'Vancouver',
  'V3F 2K1',
  'Canada'],
 ['43',
  'Lazy K Kountry Store',
  'John Steel',
  '12 Orchestra Terrace',
  'Walla Walla',
  '99362',
  'USA'],
 ['44',
  'Lehmanns Marktstand',
  'Renate Messner',
  'Magazinweg 7',
  'Frankfurt a.M.',
  '60528',
  'Germany'],
 ['45',
  "Let's Stop N Shop",
  'Jaime Yorres',
  '87 Polk St. Suite 5',
  'San Francisco',
  '94117',
  'USA'],
 ['46',
  'LILA-Supermercado',
  'Carlos González',
  'Carrera 52 con Ave. Bolívar #65-98 Llano Largo',
  'Barquisimeto',
  '3508',
  'Venezuela'],
 ['47',
  'LINO-Delicateses',
  'Felipe Izquierdo',
  'Ave. 5 de Mayo Porlamar',
  'I. de Margarita',
  '4980',
  'Venezuela'],
 ['48',
  'Lonesome Pine Restaurant',
  'Fran Wilson',
  '89 Chiaroscuro Rd.',
  'Portland',
  '97219',
  'USA'],
 ['49',
  'Magazzini Alimentari Riuniti',
  'Giovanni Rovelli',
  'Via Ludovico il Moro 22',
  'Bergamo',
  '24100',
  'Italy'],
 ['50',
  'Maison Dewey',
  'Catherine Dewey',
  'Rue Joseph-Bens 532',
  'Bruxelles',
  'B-1180',
  'Belgium'],
 ['51',
  'Mère Paillarde',
  'Jean Fresnière',
  '43 rue St. Laurent',
  'Montréal',
  'H1J 1C3',
  'Canada'],
 ['52',
  'Morgenstern Gesundkost',
  'Alexander Feuer',
  'Heerstr. 22',
  'Leipzig',
  '04179',
  'Germany'],
 ['53',
  'North/South',
  'Simon Crowther',
  'South House 300 Queensbridge',
  'London',
  'SW7 1RZ',
  'UK'],
 ['54',
  'Océano Atlántico Ltda.',
  'Yvonne Moncada',
  'Ing. Gustavo Moncada 8585 Piso 20-A',
  'Buenos Aires',
  '1010',
  'Argentina'],
 ['55',
  'Old World Delicatessen',
  'Rene Phillips',
  '2743 Bering St.',
  'Anchorage',
  '99508',
  'USA'],
 ['56',
  'Ottilies Käseladen',
  'Henriette Pfalzheim',
  'Mehrheimerstr. 369',
  'Köln',
  '50739',
  'Germany'],
 ['57',
  'Paris spécialités',
  'Marie Bertrand',
  '265, boulevard Charonne',
  'Paris',
  '75012',
  'France'],
 ['58',
  'Pericles Comidas clásicas',
  'Guillermo Fernández',
  'Calle Dr. Jorge Cash 321',
  'México D.F.',
  '05033',
  'Mexico'],
 ['59',
  'Piccolo und mehr',
  'Georg Pipps',
  'Geislweg 14',
  'Salzburg',
  '5020',
  'Austria'],
 ['60',
  'Princesa Isabel Vinhoss',
  'Isabel de Castro',
  'Estrada da saúde n. 58',
  'Lisboa',
  '1756',
  'Portugal'],
 ['61',
  'Que Delícia',
  'Bernardo Batista',
  'Rua da Panificadora, 12',
  'Rio de Janeiro',
  '02389-673',
  'Brazil'],
 ['62',
  'Queen Cozinha',
  'Lúcia Carvalho',
  'Alameda dos Canàrios, 891',
  'São Paulo',
  '05487-020',
  'Brazil'],
 ['63',
  'QUICK-Stop',
  'Horst Kloss',
  'Taucherstraße 10',
  'Cunewalde',
  '01307',
  'Germany'],
 ['64',
  'Rancho grande',
  'Sergio Gutiérrez',
  'Av. del Libertador 900',
  'Buenos Aires',
  '1010',
  'Argentina'],
 ['65',
  'Rattlesnake Canyon Grocery',
  'Paula Wilson',
  '2817 Milton Dr.',
  'Albuquerque',
  '87110',
  'USA'],
 ['66',
  'Reggiani Caseifici',
  'Maurizio Moroni',
  'Strada Provinciale 124',
  'Reggio Emilia',
  '42100',
  'Italy'],
 ['67',
  'Ricardo Adocicados',
  'Janete Limeira',
  'Av. Copacabana, 267',
  'Rio de Janeiro',
  '02389-890',
  'Brazil'],
 ['68',
  'Richter Supermarkt',
  'Michael Holz',
  'Grenzacherweg 237',
  'Genève',
  '1203',
  'Switzerland'],
 ['69',
  'Romero y tomillo',
  'Alejandra Camino',
  'Gran Vía, 1',
  'Madrid',
  '28001',
  'Spain'],
 ['70',
  'Santé Gourmet',
  'Jonas Bergulfsen',
  'Erling Skakkes gate 78',
  'Stavern',
  '4110',
  'Norway'],
 ['71',
  'Save-a-lot Markets',
  'Jose Pavarotti',
  '187 Suffolk Ln.',
  'Boise',
  '83720',
  'USA'],
 ['72',
  'Seven Seas Imports',
  'Hari Kumar',
  '90 Wadhurst Rd.',
  'London',
  'OX15 4NB',
  'UK'],
 ['73',
  'Simons bistro',
  'Jytte Petersen',
  'Vinbæltet 34',
  'København',
  '1734',
  'Denmark'],
 ['74',
  'Spécialités du monde',
  'Dominique Perrier',
  '25, rue Lauriston',
  'Paris',
  '75016',
  'France'],
 ['75',
  'Split Rail Beer & Ale',
  'Art Braunschweiger',
  'P.O. Box 555',
  'Lander',
  '82520',
  'USA'],
 ['76',
  'Suprêmes délices',
  'Pascale Cartrain',
  'Boulevard Tirou, 255',
  'Charleroi',
  'B-6000',
  'Belgium'],
 ['77',
  'The Big Cheese',
  'Liz Nixon',
  '89 Jefferson Way Suite 2',
  'Portland',
  '97201',
  'USA'],
 ['78',
  'The Cracker Box',
  'Liu Wong',
  '55 Grizzly Peak Rd.',
  'Butte',
  '59801',
  'USA'],
 ['79',
  'Toms Spezialitäten',
  'Karin Josephs',
  'Luisenstr. 48',
  'Münster',
  '44087',
  'Germany'],
 ['80',
  'Tortuga Restaurante',
  'Miguel Angel Paolino',
  'Avda. Azteca 123',
  'México D.F.',
  '05033',
  'Mexico'],
 ['81',
  'Tradição Hipermercados',
  'Anabela Domingues',
  'Av. Inês de Castro, 414',
  'São Paulo',
  '05634-030',
  'Brazil'],
 ['82',
  "Trail's Head Gourmet Provisioners",
  'Helvetius Nagy',
  '722 DaVinci Blvd.',
  'Kirkland',
  '98034',
  'USA'],
 ['83',
  'Vaffeljernet',
  'Palle Ibsen',
  'Smagsløget 45',
  'Århus',
  '8200',
  'Denmark'],
 ['84',
  'Victuailles en stock',
  'Mary Saveley',
  '2, rue du Commerce',
  'Lyon',
  '69004',
  'France'],
 ['85',
  'Vins et alcools Chevalier',
  'Paul Henriot',
  "59 rue de l'Abbaye",
  'Reims',
  '51100',
  'France'],
 ['86',
  'Die Wandernde Kuh',
  'Rita Müller',
  'Adenauerallee 900',
  'Stuttgart',
  '70563',
  'Germany'],
 ['87',
  'Wartian Herkku',
  'Pirkko Koskitalo',
  'Torikatu 38',
  'Oulu',
  '90110',
  'Finland'],
 ['88',
  'Wellington Importadora',
  'Paula Parente',
  'Rua do Mercado, 12',
  'Resende',
  '08737-363',
  'Brazil'],
 ['89',
  'White Clover Markets',
  'Karl Jablonski',
  '305 - 14th Ave. S. Suite 3B',
  'Seattle',
  '98128',
  'USA'],
 ['90',
  'Wilman Kala',
  'Matti Karttunen',
  'Keskuskatu 45',
  'Helsinki',
  '21240',
  'Finland'],
 ['91', 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland']]

In [13]:
for i, row in enumerate(rows):
    # prvni radek je nazev promenne
    if i > 0:
        #print(row[0], row[1], row[2], row[3], row[4], row[5], row[6])
        print('''INSERT INTO sqlw3s.Customers ({0}, {1}, {2}, {3}, {4}, {5}, {6}) VALUES ({7}, "{8}", "{9}", "{10}", "{11}", "{12}", "{13}");'''.format(rows[0][0], rows[0][1], rows[0][2], rows[0][3], rows[0][4], rows[0][5], rows[0][6], \
        rows[i][0], rows[i][1], rows[i][2], rows[i][3], rows[i][4], rows[i][5], rows[i][6]))
        cur.execute('''INSERT INTO sqlw3s.Customers ({0}, {1}, {2}, {3}, {4}, {5}, {6}) VALUES ({7}, "{8}", "{9}", "{10}", "{11}", "{12}", "{13}");'''.format(rows[0][0], rows[0][1], rows[0][2], rows[0][3], rows[0][4], rows[0][5], rows[0][6], \
        rows[i][0], rows[i][1], rows[i][2], rows[i][3], rows[i][4], rows[i][5], rows[i][6]))

INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (1, "Alfreds Futterkiste", "Maria Anders", "Obere Str. 57", "Berlin", "12209", "Germany");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (2, "Ana Trujillo Emparedados y helados", "Ana Trujillo", "Avda. de la Constitución 2222", "México D.F.", "05021", "Mexico");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (3, "Antonio Moreno Taquería", "Antonio Moreno", "Mataderos 2312", "México D.F.", "05023", "Mexico");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (4, "Around the Horn", "Thomas Hardy", "120 Hanover Sq.", "London", "WA1 1DP", "UK");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (5, "Berglunds snabbköp", "Christina Berglund", "Berguvsvägen 8", "Luleå", "S-958 22", "Sweden");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (6, "Blauer See Delikatessen", "Hanna Moos", "Forsterstr. 57", "Mannheim", "68306", "Germany");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (7, "Blondel père et fils", "Frédérique Citeaux", "24, place Kléber", "Strasbourg", "67000", "France");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (8, "Bólido Comidas preparadas", "Martín Sommer", "C/ Araquil, 67", "Madrid", "28023", "Spain");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (9, "Bon app'", "Laurence Lebihans", "12, rue des Bouchers", "Marseille", "13008", "France");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (10, "Bottom-Dollar Marketse", "Elizabeth Lincoln", "23 Tsawassen Blvd.", "Tsawassen", "T2F 8M4", "Canada");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (11, "B's Beverages", "Victoria Ashworth", "Fauntleroy Circus", "London", "EC2 5NT", "UK");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (12, "Cactus Comidas para llevar", "Patricio Simpson", "Cerrito 333", "Buenos Aires", "1010", "Argentina");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (13, "Centro comercial Moctezuma", "Francisco Chang", "Sierras de Granada 9993", "México D.F.", "05022", "Mexico");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (14, "Chop-suey Chinese", "Yang Wang", "Hauptstr. 29", "Bern", "3012", "Switzerland");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (15, "Comércio Mineiro", "Pedro Afonso", "Av. dos Lusíadas, 23", "São Paulo", "05432-043", "Brazil");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (16, "Consolidated Holdings", "Elizabeth Brown", "Berkeley Gardens 12 Brewery", "London", "WX1 6LT", "UK");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (17, "Drachenblut Delikatessend", "Sven Ottlieb", "Walserweg 21", "Aachen", "52066", "Germany");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (18, "Du monde entier", "Janine Labrune", "67, rue des Cinquante Otages", "Nantes", "44000", "France");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (19, "Eastern Connection", "Ann Devon", "35 King George", "London", "WX3 6FW", "UK");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (20, "Ernst Handel", "Roland Mendel", "Kirchgasse 6", "Graz", "8010", "Austria");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (21, "Familia Arquibaldo", "Aria Cruz", "Rua Orós, 92", "São Paulo", "05442-030", "Brazil");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (22, "FISSA Fabrica Inter. Salchichas S.A.", "Diego Roel", "C/ Moralzarzal, 86", "Madrid", "28034", "Spain");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (23, "Folies gourmandes", "Martine Rancé", "184, chaussée de Tournai", "Lille", "59000", "France");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (24, "Folk och fä HB", "Maria Larsson", "Åkergatan 24", "Bräcke", "S-844 67", "Sweden");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (25, "Frankenversand", "Peter Franken", "Berliner Platz 43", "München", "80805", "Germany");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (26, "France restauration", "Carine Schmitt", "54, rue Royale", "Nantes", "44000", "France");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (27, "Franchi S.p.A.", "Paolo Accorti", "Via Monte Bianco 34", "Torino", "10100", "Italy");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (28, "Furia Bacalhau e Frutos do Mar", "Lino Rodriguez", "Jardim das rosas n. 32", "Lisboa", "1675", "Portugal");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (29, "Galería del gastrónomo", "Eduardo Saavedra", "Rambla de Cataluña, 23", "Barcelona", "08022", "Spain");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (30, "Godos Cocina Típica", "José Pedro Freyre", "C/ Romero, 33", "Sevilla", "41101", "Spain");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (31, "Gourmet Lanchonetes", "André Fonseca", "Av. Brasil, 442", "Campinas", "04876-786", "Brazil");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (32, "Great Lakes Food Market", "Howard Snyder", "2732 Baker Blvd.", "Eugene", "97403", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (33, "GROSELLA-Restaurante", "Manuel Pereira", "5ª Ave. Los Palos Grandes", "Caracas", "1081", "Venezuela");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (34, "Hanari Carnes", "Mario Pontes", "Rua do Paço, 67", "Rio de Janeiro", "05454-876", "Brazil");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (35, "HILARIÓN-Abastos", "Carlos Hernández", "Carrera 22 con Ave. Carlos Soublette #8-35", "San Cristóbal", "5022", "Venezuela");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (36, "Hungry Coyote Import Store", "Yoshi Latimer", "City Center Plaza 516 Main St.", "Elgin", "97827", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (37, "Hungry Owl All-Night Grocers", "Patricia McKenna", "8 Johnstown Road", "Cork", "", "Ireland");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (38, "Island Trading", "Helen Bennett", "Garden House Crowther Way", "Cowes", "PO31 7PJ", "UK");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (39, "Königlich Essen", "Philip Cramer", "Maubelstr. 90", "Brandenburg", "14776", "Germany");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (40, "La corne d'abondance", "Daniel Tonini", "67, avenue de l'Europe", "Versailles", "78000", "France");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (41, "La maison d'Asie", "Annette Roulet", "1 rue Alsace-Lorraine", "Toulouse", "31000", "France");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (42, "Laughing Bacchus Wine Cellars", "Yoshi Tannamuri", "1900 Oak St.", "Vancouver", "V3F 2K1", "Canada");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (43, "Lazy K Kountry Store", "John Steel", "12 Orchestra Terrace", "Walla Walla", "99362", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (44, "Lehmanns Marktstand", "Renate Messner", "Magazinweg 7", "Frankfurt a.M.", "60528", "Germany");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (45, "Let's Stop N Shop", "Jaime Yorres", "87 Polk St. Suite 5", "San Francisco", "94117", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (46, "LILA-Supermercado", "Carlos González", "Carrera 52 con Ave. Bolívar #65-98 Llano Largo", "Barquisimeto", "3508", "Venezuela");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (47, "LINO-Delicateses", "Felipe Izquierdo", "Ave. 5 de Mayo Porlamar", "I. de Margarita", "4980", "Venezuela");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (48, "Lonesome Pine Restaurant", "Fran Wilson", "89 Chiaroscuro Rd.", "Portland", "97219", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (49, "Magazzini Alimentari Riuniti", "Giovanni Rovelli", "Via Ludovico il Moro 22", "Bergamo", "24100", "Italy");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (50, "Maison Dewey", "Catherine Dewey", "Rue Joseph-Bens 532", "Bruxelles", "B-1180", "Belgium");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (51, "Mère Paillarde", "Jean Fresnière", "43 rue St. Laurent", "Montréal", "H1J 1C3", "Canada");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (52, "Morgenstern Gesundkost", "Alexander Feuer", "Heerstr. 22", "Leipzig", "04179", "Germany");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (53, "North/South", "Simon Crowther", "South House 300 Queensbridge", "London", "SW7 1RZ", "UK");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (54, "Océano Atlántico Ltda.", "Yvonne Moncada", "Ing. Gustavo Moncada 8585 Piso 20-A", "Buenos Aires", "1010", "Argentina");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (55, "Old World Delicatessen", "Rene Phillips", "2743 Bering St.", "Anchorage", "99508", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (56, "Ottilies Käseladen", "Henriette Pfalzheim", "Mehrheimerstr. 369", "Köln", "50739", "Germany");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (57, "Paris spécialités", "Marie Bertrand", "265, boulevard Charonne", "Paris", "75012", "France");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (58, "Pericles Comidas clásicas", "Guillermo Fernández", "Calle Dr. Jorge Cash 321", "México D.F.", "05033", "Mexico");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (59, "Piccolo und mehr", "Georg Pipps", "Geislweg 14", "Salzburg", "5020", "Austria");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (60, "Princesa Isabel Vinhoss", "Isabel de Castro", "Estrada da saúde n. 58", "Lisboa", "1756", "Portugal");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (61, "Que Delícia", "Bernardo Batista", "Rua da Panificadora, 12", "Rio de Janeiro", "02389-673", "Brazil");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (62, "Queen Cozinha", "Lúcia Carvalho", "Alameda dos Canàrios, 891", "São Paulo", "05487-020", "Brazil");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (63, "QUICK-Stop", "Horst Kloss", "Taucherstraße 10", "Cunewalde", "01307", "Germany");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (64, "Rancho grande", "Sergio Gutiérrez", "Av. del Libertador 900", "Buenos Aires", "1010", "Argentina");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (65, "Rattlesnake Canyon Grocery", "Paula Wilson", "2817 Milton Dr.", "Albuquerque", "87110", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (66, "Reggiani Caseifici", "Maurizio Moroni", "Strada Provinciale 124", "Reggio Emilia", "42100", "Italy");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (67, "Ricardo Adocicados", "Janete Limeira", "Av. Copacabana, 267", "Rio de Janeiro", "02389-890", "Brazil");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (68, "Richter Supermarkt", "Michael Holz", "Grenzacherweg 237", "Genève", "1203", "Switzerland");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (69, "Romero y tomillo", "Alejandra Camino", "Gran Vía, 1", "Madrid", "28001", "Spain");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (70, "Santé Gourmet", "Jonas Bergulfsen", "Erling Skakkes gate 78", "Stavern", "4110", "Norway");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (71, "Save-a-lot Markets", "Jose Pavarotti", "187 Suffolk Ln.", "Boise", "83720", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (72, "Seven Seas Imports", "Hari Kumar", "90 Wadhurst Rd.", "London", "OX15 4NB", "UK");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (73, "Simons bistro", "Jytte Petersen", "Vinbæltet 34", "København", "1734", "Denmark");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (74, "Spécialités du monde", "Dominique Perrier", "25, rue Lauriston", "Paris", "75016", "France");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (75, "Split Rail Beer & Ale", "Art Braunschweiger", "P.O. Box 555", "Lander", "82520", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (76, "Suprêmes délices", "Pascale Cartrain", "Boulevard Tirou, 255", "Charleroi", "B-6000", "Belgium");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (77, "The Big Cheese", "Liz Nixon", "89 Jefferson Way Suite 2", "Portland", "97201", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (78, "The Cracker Box", "Liu Wong", "55 Grizzly Peak Rd.", "Butte", "59801", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (79, "Toms Spezialitäten", "Karin Josephs", "Luisenstr. 48", "Münster", "44087", "Germany");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (80, "Tortuga Restaurante", "Miguel Angel Paolino", "Avda. Azteca 123", "México D.F.", "05033", "Mexico");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (81, "Tradição Hipermercados", "Anabela Domingues", "Av. Inês de Castro, 414", "São Paulo", "05634-030", "Brazil");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (82, "Trail's Head Gourmet Provisioners", "Helvetius Nagy", "722 DaVinci Blvd.", "Kirkland", "98034", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (83, "Vaffeljernet", "Palle Ibsen", "Smagsløget 45", "Århus", "8200", "Denmark");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (84, "Victuailles en stock", "Mary Saveley", "2, rue du Commerce", "Lyon", "69004", "France");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (85, "Vins et alcools Chevalier", "Paul Henriot", "59 rue de l'Abbaye", "Reims", "51100", "France");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (86, "Die Wandernde Kuh", "Rita Müller", "Adenauerallee 900", "Stuttgart", "70563", "Germany");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (87, "Wartian Herkku", "Pirkko Koskitalo", "Torikatu 38", "Oulu", "90110", "Finland");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (88, "Wellington Importadora", "Paula Parente", "Rua do Mercado, 12", "Resende", "08737-363", "Brazil");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (89, "White Clover Markets", "Karl Jablonski", "305 - 14th Ave. S. Suite 3B", "Seattle", "98128", "USA");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (90, "Wilman Kala", "Matti Karttunen", "Keskuskatu 45", "Helsinki", "21240", "Finland");
INSERT INTO sqlw3s.Customers (CustomerID, CustomerName, ContactName, Address, City, PostalCode, Country) VALUES (91, "Wolski", "Zbyszek", "ul. Filtrowa 68", "Walla", "01-012", "Poland");

In [14]:
conn.commit()

In [15]:
cur.execute('select * from sqlw3s.Customers;')
result = cur.fetchall();
result

((1,
  'Alfreds Futterkiste',
  'Maria Anders',
  'Obere Str. 57',
  'Berlin',
  '12209',
  'Germany'),
 (2,
  'Ana Trujillo Emparedados y helados',
  'Ana Trujillo',
  'Avda. de la Constitución 2222',
  'México D.F.',
  '05021',
  'Mexico'),
 (3,
  'Antonio Moreno Taquería',
  'Antonio Moreno',
  'Mataderos 2312',
  'México D.F.',
  '05023',
  'Mexico'),
 (4,
  'Around the Horn',
  'Thomas Hardy',
  '120 Hanover Sq.',
  'London',
  'WA1 1DP',
  'UK'),
 (5,
  'Berglunds snabbköp',
  'Christina Berglund',
  'Berguvsvägen 8',
  'Luleå',
  'S-958 22',
  'Sweden'),
 (6,
  'Blauer See Delikatessen',
  'Hanna Moos',
  'Forsterstr. 57',
  'Mannheim',
  '68306',
  'Germany'),
 (7,
  'Blondel père et fils',
  'Frédérique Citeaux',
  '24, place Kléber',
  'Strasbourg',
  '67000',
  'France'),
 (8,
  'Bólido Comidas preparadas',
  'Martín Sommer',
  'C/ Araquil, 67',
  'Madrid',
  '28023',
  'Spain'),
 (9,
  "Bon app'",
  'Laurence Lebihans',
  '12, rue des Bouchers',
  'Marseille',
  '13008',
  'France'),
 (10,
  'Bottom-Dollar Marketse',
  'Elizabeth Lincoln',
  '23 Tsawassen Blvd.',
  'Tsawassen',
  'T2F 8M4',
  'Canada'),
 (11,
  "B's Beverages",
  'Victoria Ashworth',
  'Fauntleroy Circus',
  'London',
  'EC2 5NT',
  'UK'),
 (12,
  'Cactus Comidas para llevar',
  'Patricio Simpson',
  'Cerrito 333',
  'Buenos Aires',
  '1010',
  'Argentina'),
 (13,
  'Centro comercial Moctezuma',
  'Francisco Chang',
  'Sierras de Granada 9993',
  'México D.F.',
  '05022',
  'Mexico'),
 (14,
  'Chop-suey Chinese',
  'Yang Wang',
  'Hauptstr. 29',
  'Bern',
  '3012',
  'Switzerland'),
 (15,
  'Comércio Mineiro',
  'Pedro Afonso',
  'Av. dos Lusíadas, 23',
  'São Paulo',
  '05432-043',
  'Brazil'),
 (16,
  'Consolidated Holdings',
  'Elizabeth Brown',
  'Berkeley Gardens 12 Brewery',
  'London',
  'WX1 6LT',
  'UK'),
 (17,
  'Drachenblut Delikatessend',
  'Sven Ottlieb',
  'Walserweg 21',
  'Aachen',
  '52066',
  'Germany'),
 (18,
  'Du monde entier',
  'Janine Labrune',
  '67, rue des Cinquante Otages',
  'Nantes',
  '44000',
  'France'),
 (19,
  'Eastern Connection',
  'Ann Devon',
  '35 King George',
  'London',
  'WX3 6FW',
  'UK'),
 (20,
  'Ernst Handel',
  'Roland Mendel',
  'Kirchgasse 6',
  'Graz',
  '8010',
  'Austria'),
 (21,
  'Familia Arquibaldo',
  'Aria Cruz',
  'Rua Orós, 92',
  'São Paulo',
  '05442-030',
  'Brazil'),
 (22,
  'FISSA Fabrica Inter. Salchichas S.A.',
  'Diego Roel',
  'C/ Moralzarzal, 86',
  'Madrid',
  '28034',
  'Spain'),
 (23,
  'Folies gourmandes',
  'Martine Rancé',
  '184, chaussée de Tournai',
  'Lille',
  '59000',
  'France'),
 (24,
  'Folk och fä HB',
  'Maria Larsson',
  'Åkergatan 24',
  'Bräcke',
  'S-844 67',
  'Sweden'),
 (25,
  'Frankenversand',
  'Peter Franken',
  'Berliner Platz 43',
  'München',
  '80805',
  'Germany'),
 (26,
  'France restauration',
  'Carine Schmitt',
  '54, rue Royale',
  'Nantes',
  '44000',
  'France'),
 (27,
  'Franchi S.p.A.',
  'Paolo Accorti',
  'Via Monte Bianco 34',
  'Torino',
  '10100',
  'Italy'),
 (28,
  'Furia Bacalhau e Frutos do Mar',
  'Lino Rodriguez',
  'Jardim das rosas n. 32',
  'Lisboa',
  '1675',
  'Portugal'),
 (29,
  'Galería del gastrónomo',
  'Eduardo Saavedra',
  'Rambla de Cataluña, 23',
  'Barcelona',
  '08022',
  'Spain'),
 (30,
  'Godos Cocina Típica',
  'José Pedro Freyre',
  'C/ Romero, 33',
  'Sevilla',
  '41101',
  'Spain'),
 (31,
  'Gourmet Lanchonetes',
  'André Fonseca',
  'Av. Brasil, 442',
  'Campinas',
  '04876-786',
  'Brazil'),
 (32,
  'Great Lakes Food Market',
  'Howard Snyder',
  '2732 Baker Blvd.',
  'Eugene',
  '97403',
  'USA'),
 (33,
  'GROSELLA-Restaurante',
  'Manuel Pereira',
  '5ª Ave. Los Palos Grandes',
  'Caracas',
  '1081',
  'Venezuela'),
 (34,
  'Hanari Carnes',
  'Mario Pontes',
  'Rua do Paço, 67',
  'Rio de Janeiro',
  '05454-876',
  'Brazil'),
 (35,
  'HILARIÓN-Abastos',
  'Carlos Hernández',
  'Carrera 22 con Ave. Carlos Soublette #8-35',
  'San Cristóbal',
  '5022',
  'Venezuela'),
 (36,
  'Hungry Coyote Import Store',
  'Yoshi Latimer',
  'City Center Plaza 516 Main St.',
  'Elgin',
  '97827',
  'USA'),
 (37,
  'Hungry Owl All-Night Grocers',
  'Patricia McKenna',
  '8 Johnstown Road',
  'Cork',
  '',
  'Ireland'),
 (38,
  'Island Trading',
  'Helen Bennett',
  'Garden House Crowther Way',
  'Cowes',
  'PO31 7PJ',
  'UK'),
 (39,
  'Königlich Essen',
  'Philip Cramer',
  'Maubelstr. 90',
  'Brandenburg',
  '14776',
  'Germany'),
 (40,
  "La corne d'abondance",
  'Daniel Tonini',
  "67, avenue de l'Europe",
  'Versailles',
  '78000',
  'France'),
 (41,
  "La maison d'Asie",
  'Annette Roulet',
  '1 rue Alsace-Lorraine',
  'Toulouse',
  '31000',
  'France'),
 (42,
  'Laughing Bacchus Wine Cellars',
  'Yoshi Tannamuri',
  '1900 Oak St.',
  'Vancouver',
  'V3F 2K1',
  'Canada'),
 (43,
  'Lazy K Kountry Store',
  'John Steel',
  '12 Orchestra Terrace',
  'Walla Walla',
  '99362',
  'USA'),
 (44,
  'Lehmanns Marktstand',
  'Renate Messner',
  'Magazinweg 7',
  'Frankfurt a.M.',
  '60528',
  'Germany'),
 (45,
  "Let's Stop N Shop",
  'Jaime Yorres',
  '87 Polk St. Suite 5',
  'San Francisco',
  '94117',
  'USA'),
 (46,
  'LILA-Supermercado',
  'Carlos González',
  'Carrera 52 con Ave. Bolívar #65-98 Llano Largo',
  'Barquisimeto',
  '3508',
  'Venezuela'),
 (47,
  'LINO-Delicateses',
  'Felipe Izquierdo',
  'Ave. 5 de Mayo Porlamar',
  'I. de Margarita',
  '4980',
  'Venezuela'),
 (48,
  'Lonesome Pine Restaurant',
  'Fran Wilson',
  '89 Chiaroscuro Rd.',
  'Portland',
  '97219',
  'USA'),
 (49,
  'Magazzini Alimentari Riuniti',
  'Giovanni Rovelli',
  'Via Ludovico il Moro 22',
  'Bergamo',
  '24100',
  'Italy'),
 (50,
  'Maison Dewey',
  'Catherine Dewey',
  'Rue Joseph-Bens 532',
  'Bruxelles',
  'B-1180',
  'Belgium'),
 (51,
  'Mère Paillarde',
  'Jean Fresnière',
  '43 rue St. Laurent',
  'Montréal',
  'H1J 1C3',
  'Canada'),
 (52,
  'Morgenstern Gesundkost',
  'Alexander Feuer',
  'Heerstr. 22',
  'Leipzig',
  '04179',
  'Germany'),
 (53,
  'North/South',
  'Simon Crowther',
  'South House 300 Queensbridge',
  'London',
  'SW7 1RZ',
  'UK'),
 (54,
  'Océano Atlántico Ltda.',
  'Yvonne Moncada',
  'Ing. Gustavo Moncada 8585 Piso 20-A',
  'Buenos Aires',
  '1010',
  'Argentina'),
 (55,
  'Old World Delicatessen',
  'Rene Phillips',
  '2743 Bering St.',
  'Anchorage',
  '99508',
  'USA'),
 (56,
  'Ottilies Käseladen',
  'Henriette Pfalzheim',
  'Mehrheimerstr. 369',
  'Köln',
  '50739',
  'Germany'),
 (57,
  'Paris spécialités',
  'Marie Bertrand',
  '265, boulevard Charonne',
  'Paris',
  '75012',
  'France'),
 (58,
  'Pericles Comidas clásicas',
  'Guillermo Fernández',
  'Calle Dr. Jorge Cash 321',
  'México D.F.',
  '05033',
  'Mexico'),
 (59,
  'Piccolo und mehr',
  'Georg Pipps',
  'Geislweg 14',
  'Salzburg',
  '5020',
  'Austria'),
 (60,
  'Princesa Isabel Vinhoss',
  'Isabel de Castro',
  'Estrada da saúde n. 58',
  'Lisboa',
  '1756',
  'Portugal'),
 (61,
  'Que Delícia',
  'Bernardo Batista',
  'Rua da Panificadora, 12',
  'Rio de Janeiro',
  '02389-673',
  'Brazil'),
 (62,
  'Queen Cozinha',
  'Lúcia Carvalho',
  'Alameda dos Canàrios, 891',
  'São Paulo',
  '05487-020',
  'Brazil'),
 (63,
  'QUICK-Stop',
  'Horst Kloss',
  'Taucherstraße 10',
  'Cunewalde',
  '01307',
  'Germany'),
 (64,
  'Rancho grande',
  'Sergio Gutiérrez',
  'Av. del Libertador 900',
  'Buenos Aires',
  '1010',
  'Argentina'),
 (65,
  'Rattlesnake Canyon Grocery',
  'Paula Wilson',
  '2817 Milton Dr.',
  'Albuquerque',
  '87110',
  'USA'),
 (66,
  'Reggiani Caseifici',
  'Maurizio Moroni',
  'Strada Provinciale 124',
  'Reggio Emilia',
  '42100',
  'Italy'),
 (67,
  'Ricardo Adocicados',
  'Janete Limeira',
  'Av. Copacabana, 267',
  'Rio de Janeiro',
  '02389-890',
  'Brazil'),
 (68,
  'Richter Supermarkt',
  'Michael Holz',
  'Grenzacherweg 237',
  'Genève',
  '1203',
  'Switzerland'),
 (69,
  'Romero y tomillo',
  'Alejandra Camino',
  'Gran Vía, 1',
  'Madrid',
  '28001',
  'Spain'),
 (70,
  'Santé Gourmet',
  'Jonas Bergulfsen',
  'Erling Skakkes gate 78',
  'Stavern',
  '4110',
  'Norway'),
 (71,
  'Save-a-lot Markets',
  'Jose Pavarotti',
  '187 Suffolk Ln.',
  'Boise',
  '83720',
  'USA'),
 (72,
  'Seven Seas Imports',
  'Hari Kumar',
  '90 Wadhurst Rd.',
  'London',
  'OX15 4NB',
  'UK'),
 (73,
  'Simons bistro',
  'Jytte Petersen',
  'Vinbæltet 34',
  'København',
  '1734',
  'Denmark'),
 (74,
  'Spécialités du monde',
  'Dominique Perrier',
  '25, rue Lauriston',
  'Paris',
  '75016',
  'France'),
 (75,
  'Split Rail Beer & Ale',
  'Art Braunschweiger',
  'P.O. Box 555',
  'Lander',
  '82520',
  'USA'),
 (76,
  'Suprêmes délices',
  'Pascale Cartrain',
  'Boulevard Tirou, 255',
  'Charleroi',
  'B-6000',
  'Belgium'),
 (77,
  'The Big Cheese',
  'Liz Nixon',
  '89 Jefferson Way Suite 2',
  'Portland',
  '97201',
  'USA'),
 (78,
  'The Cracker Box',
  'Liu Wong',
  '55 Grizzly Peak Rd.',
  'Butte',
  '59801',
  'USA'),
 (79,
  'Toms Spezialitäten',
  'Karin Josephs',
  'Luisenstr. 48',
  'Münster',
  '44087',
  'Germany'),
 (80,
  'Tortuga Restaurante',
  'Miguel Angel Paolino',
  'Avda. Azteca 123',
  'México D.F.',
  '05033',
  'Mexico'),
 (81,
  'Tradição Hipermercados',
  'Anabela Domingues',
  'Av. Inês de Castro, 414',
  'São Paulo',
  '05634-030',
  'Brazil'),
 (82,
  "Trail's Head Gourmet Provisioners",
  'Helvetius Nagy',
  '722 DaVinci Blvd.',
  'Kirkland',
  '98034',
  'USA'),
 (83,
  'Vaffeljernet',
  'Palle Ibsen',
  'Smagsløget 45',
  'Århus',
  '8200',
  'Denmark'),
 (84,
  'Victuailles en stock',
  'Mary Saveley',
  '2, rue du Commerce',
  'Lyon',
  '69004',
  'France'),
 (85,
  'Vins et alcools Chevalier',
  'Paul Henriot',
  "59 rue de l'Abbaye",
  'Reims',
  '51100',
  'France'),
 (86,
  'Die Wandernde Kuh',
  'Rita Müller',
  'Adenauerallee 900',
  'Stuttgart',
  '70563',
  'Germany'),
 (87,
  'Wartian Herkku',
  'Pirkko Koskitalo',
  'Torikatu 38',
  'Oulu',
  '90110',
  'Finland'),
 (88,
  'Wellington Importadora',
  'Paula Parente',
  'Rua do Mercado, 12',
  'Resende',
  '08737-363',
  'Brazil'),
 (89,
  'White Clover Markets',
  'Karl Jablonski',
  '305 - 14th Ave. S. Suite 3B',
  'Seattle',
  '98128',
  'USA'),
 (90,
  'Wilman Kala',
  'Matti Karttunen',
  'Keskuskatu 45',
  'Helsinki',
  '21240',
  'Finland'),
 (91, 'Wolski', 'Zbyszek', 'ul. Filtrowa 68', 'Walla', '01-012', 'Poland'))

In [16]:
#cur.execute('TRUNCATE sqlw3s.Customers;')
conn.commit()

In [17]:
conn.close()